//! TypeID primitive — thin wrapper around the [`mti`] crate.
//!
//! Implements the cross-language kit API SHAPE defined in
//! `docs/adr/0001-typeid-primitive.md` for Rust:
//!
//! - [`new`] — generate a `prefix_<26-char-base32>` string from a prefix.
//! - [`parse`] — round-trip an existing canonical string back to its parts.
//! - [`Typed<T>`] — compile-time-prefix-safe newtype, parameterised by a
//!   [`Prefix`] marker type carrying `const PREFIX: &'static str`.
//! - serde [`Serialize`] / [`Deserialize`] for [`Typed<T>`] — the wire form
//!   is the **bare typeid string**, never a struct/object.
//! - [`IdError`] — variants for invalid prefix, invalid suffix, and
//!   prefix-mismatch (typed parse).
//!
//! URI composition (`<scheme>://<entity-type>/<typeid>`) is **not** part of
//! this module. Adopters compose the canonical string with `hop-top-cite`
//! directly. This keeps the typeid primitive free of any transitive URI
//! dependency.
//!
//! # Spec
//!
//! Wraps the Jetify TypeID specification **v0.3.0** (UUIDv7 by default,
//! 26-char Crockford base32 suffix). See ADR 0001 for the full rationale.
//!
//! # Bus-factor warning
//!
//! The upstream [`mti`](https://github.com/Govcraft/mti) crate currently has
//! a **single active contributor** and is the only actively-maintained
//! Jetify-spec-compliant Rust implementation. ADR 0001 accepts this risk
//! with the following mitigations:
//!
//! 1. The dependency surface in this module is small and isolated; if the
//!    crate goes unmaintained we can vendor it or swap to a replacement
//!    without touching adopters.
//! 2. Upstream activity is reviewed at every kit release. If there is no
//!    commit for 12 months and an open critical bug, the kit maintainers
//!    will publish a fork under the kit org (dual Apache-2.0 / MIT
//!    licensing is preserved by upstream).
//!
//! Carry this warning forward when reading or extending the module.
//!
//! # Example
//!
//! ```
//! use hop_top_kit::id::{new, parse};
//!
//! let id = new("task").unwrap();
//! assert!(id.starts_with("task_"));
//!
//! let parsed = parse(&id).unwrap();
//! assert_eq!(parsed.prefix, "task");
//! assert_eq!(parsed.uuid.get_version_num(), 7);
//! ```

use std::fmt;
use std::marker::PhantomData;
use std::str::FromStr;

use mti::prelude::{MagicTypeId, MagicTypeIdError, MagicTypeIdExt, TypeIdSuffix, V7};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use thiserror::Error;
use uuid::Uuid;

/// Errors produced by the kit typeid primitive.
///
/// Variants are intentionally cross-language: the same three failure modes
/// surface in the Go, Python, TypeScript and PHP bindings, so adopters that
/// dispatch on error kind can write parallel logic across SDKs.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum IdError {
    /// The prefix did not match the Jetify TypeID grammar
    /// (`^[a-z]([a-z0-9_]*[a-z0-9])?$`, max 63 chars), or was rejected by the
    /// upstream parser for any other prefix-related reason.
    #[error("invalid typeid prefix: {0}")]
    InvalidPrefix(String),

    /// The suffix is not a valid 26-character Crockford base32 encoding of a
    /// UUID, or otherwise failed validation.
    #[error("invalid typeid suffix: {0}")]
    InvalidSuffix(String),

    /// A [`Typed<T>`] parse received a canonical typeid whose prefix did not
    /// match `T::PREFIX`.
    #[error("typeid prefix mismatch: expected `{expected}`, got `{got}`")]
    PrefixMismatch {
        /// The prefix expected by the typed wrapper (`T::PREFIX`).
        expected: String,
        /// The prefix carried in the parsed string.
        got: String,
    },
}

impl From<MagicTypeIdError> for IdError {
    fn from(err: MagicTypeIdError) -> Self {
        match err {
            MagicTypeIdError::Prefix(e) => Self::InvalidPrefix(e.to_string()),
            MagicTypeIdError::Suffix(e) => Self::InvalidSuffix(e.to_string()),
        }
    }
}

/// Result of parsing a canonical typeid string.
///
/// `uuid` is the raw 128-bit identifier decoded from the suffix. For typeids
/// generated by [`new`], this is a UUIDv7 (time-ordered).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Parsed {
    /// The prefix component (`""` for prefix-less typeids).
    pub prefix: String,
    /// The decoded UUID payload.
    pub uuid: Uuid,
}

/// Generate a new canonical typeid string for `prefix`, with a freshly-minted
/// UUIDv7 suffix.
///
/// Returns the bare typeid string (e.g. `task_01j…`). The suffix is always a
/// 26-char Crockford base32 encoding; the canonical form is
/// `<prefix>_<suffix>`.
///
/// # Errors
///
/// Returns [`IdError::InvalidPrefix`] if `prefix` does not match the Jetify
/// TypeID grammar `^[a-z]([a-z0-9_]*[a-z0-9])?$` (max 63 chars). The empty
/// prefix is **rejected** here so callers always get a self-describing ID;
/// if you genuinely want a suffix-only typeid, build it through the upstream
/// crate.
///
/// # Example
///
/// ```
/// use hop_top_kit::id::new;
///
/// let id = new("invoice").unwrap();
/// assert!(id.starts_with("invoice_"));
/// assert_eq!(id.len(), "invoice_".len() + 26);
/// ```
pub fn new(prefix: &str) -> Result<String, IdError> {
    if prefix.is_empty() {
        return Err(IdError::InvalidPrefix(
            "prefix must not be empty".to_owned(),
        ));
    }
    let id = prefix.try_create_type_id::<V7>()?;
    Ok(id.to_string())
}

/// Parse a canonical typeid string into its prefix and UUID components.
///
/// # Errors
///
/// - [`IdError::InvalidPrefix`] if the prefix fails the Jetify TypeID
///   grammar.
/// - [`IdError::InvalidSuffix`] if the suffix is not a valid 26-char
///   base32-encoded UUID.
///
/// # Example
///
/// ```
/// use hop_top_kit::id::{new, parse};
///
/// let id = new("user").unwrap();
/// let parsed = parse(&id).unwrap();
/// assert_eq!(parsed.prefix, "user");
/// ```
pub fn parse(s: &str) -> Result<Parsed, IdError> {
    let mti = MagicTypeId::from_str(s)?;
    Ok(Parsed {
        prefix: mti.prefix().as_str().to_owned(),
        uuid: mti.suffix().to_uuid(),
    })
}

/// Marker trait pinning a typeid prefix at the type level.
///
/// Implement this on a zero-sized marker struct per entity:
///
/// ```
/// use hop_top_kit::id::{Prefix, Typed};
///
/// #[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// pub struct Task;
/// impl Prefix for Task {
///     const PREFIX: &'static str = "task";
/// }
///
/// pub type TaskId = Typed<Task>;
///
/// let id = TaskId::new().unwrap();
/// assert!(id.as_str().starts_with("task_"));
/// ```
pub trait Prefix {
    /// The canonical prefix this typed ID wears at runtime.
    const PREFIX: &'static str;
}

/// Compile-time-prefix-safe typeid newtype.
///
/// `Typed<T>` wraps the canonical typeid string and ties the prefix to the
/// type system through `T: Prefix`. Functions that take `Typed<Task>` will
/// only accept task IDs; the compiler enforces this regardless of the
/// underlying string.
///
/// # Serde wire form
///
/// `Typed<T>` serialises as the **bare typeid string** (e.g. `"task_01j…"`),
/// never as an object. Deserialisation validates both that the input parses
/// as a typeid **and** that its prefix equals `T::PREFIX`; otherwise an
/// [`IdError::PrefixMismatch`] is surfaced via serde.
///
/// # Example
///
/// ```
/// use hop_top_kit::id::{Prefix, Typed};
///
/// pub struct Invoice;
/// impl Prefix for Invoice {
///     const PREFIX: &'static str = "invoice";
/// }
///
/// let id: Typed<Invoice> = Typed::new().unwrap();
/// let round = Typed::<Invoice>::parse(id.as_str()).unwrap();
/// assert_eq!(id, round);
/// ```
pub struct Typed<T: Prefix>(String, PhantomData<T>);

impl<T: Prefix> Typed<T> {
    /// Generate a new `Typed<T>` with `T::PREFIX` and a fresh UUIDv7.
    ///
    /// # Errors
    ///
    /// Returns [`IdError::InvalidPrefix`] if `T::PREFIX` does not match the
    /// Jetify TypeID grammar. This is a "fix the marker type" error, not
    /// something callers can recover from at runtime.
    pub fn new() -> Result<Self, IdError> {
        let s = new(T::PREFIX)?;
        Ok(Self(s, PhantomData))
    }

    /// Parse a canonical typeid string, requiring its prefix to equal
    /// `T::PREFIX`.
    ///
    /// # Errors
    ///
    /// - [`IdError::InvalidPrefix`] / [`IdError::InvalidSuffix`] if the
    ///   string is not a syntactically valid typeid.
    /// - [`IdError::PrefixMismatch`] if the prefix does not equal
    ///   `T::PREFIX`.
    pub fn parse(s: &str) -> Result<Self, IdError> {
        let parsed = parse(s)?;
        if parsed.prefix != T::PREFIX {
            return Err(IdError::PrefixMismatch {
                expected: T::PREFIX.to_owned(),
                got: parsed.prefix,
            });
        }
        Ok(Self(s.to_owned(), PhantomData))
    }

    /// Borrow the canonical typeid string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Consume `self` and return the canonical typeid string.
    #[must_use]
    pub fn into_inner(self) -> String {
        self.0
    }
}

impl<T: Prefix> fmt::Debug for Typed<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Typed").field(&self.0).finish()
    }
}

impl<T: Prefix> fmt::Display for Typed<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl<T: Prefix> Clone for Typed<T> {
    fn clone(&self) -> Self {
        Self(self.0.clone(), PhantomData)
    }
}

impl<T: Prefix> PartialEq for Typed<T> {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl<T: Prefix> Eq for Typed<T> {}

impl<T: Prefix> std::hash::Hash for Typed<T> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

impl<T: Prefix> AsRef<str> for Typed<T> {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

impl<T: Prefix> FromStr for Typed<T> {
    type Err = IdError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::parse(s)
    }
}

impl<T: Prefix> Serialize for Typed<T> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&self.0)
    }
}

impl<'de, T: Prefix> Deserialize<'de> for Typed<T> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Self::parse(&s).map_err(serde::de::Error::custom)
    }
}

/// Build a canonical typeid string deterministically from an explicit
/// `prefix` and `uuid`. Useful for fixtures and cross-language parity
/// tests where both sides must agree on the encoded form for a pinned
/// input (tlc T-0753).
///
/// # Errors
///
/// Returns [`IdError::InvalidPrefix`] if `prefix` is empty or violates the
/// Jetify TypeID grammar. The empty-prefix rejection matches [`new`]: the
/// kit's Rust wrapper requires a self-describing prefix on every id.
///
/// # Example
///
/// ```
/// use hop_top_kit::id::{from_uuid, parse};
/// use uuid::Uuid;
///
/// let uuid = Uuid::parse_str("01940000-0000-7000-8000-000000000000").unwrap();
/// let s = from_uuid("task", uuid).unwrap();
/// assert_eq!(s, "task_01jg000000e008000000000000");
/// let parsed = parse(&s).unwrap();
/// assert_eq!(parsed.uuid, uuid);
/// ```
pub fn from_uuid(prefix: &str, uuid: Uuid) -> Result<String, IdError> {
    if prefix.is_empty() {
        return Err(IdError::InvalidPrefix(
            "prefix must not be empty".to_owned(),
        ));
    }
    let suffix = TypeIdSuffix::from(uuid);
    let id = prefix.try_create_type_id_with_suffix::<V7>(suffix)?;
    Ok(id.to_string())
}

/// Internal helper retained for parity fixture verification (T-0753).
/// Mirrors [`from_uuid`] but bypasses the kit's empty-prefix rejection so
/// the parity test suite can probe both paths from the same construction
/// site without needing two crates' worth of test plumbing.
#[doc(hidden)]
pub(crate) fn __test_only_from_uuid(prefix: &str, uuid: Uuid) -> Result<String, IdError> {
    let suffix = TypeIdSuffix::from(uuid);
    let id = prefix.try_create_type_id_with_suffix::<V7>(suffix)?;
    Ok(id.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    // ------------------------------------------------------------------
    // Canonical fixtures — these UUID inputs are the cross-language parity
    // anchors for T-0753. Do NOT change them; future SDKs (py/ts/php/go)
    // must consume the same triples and produce matching typeid strings.
    // ------------------------------------------------------------------
    const FIXTURE_TASK_UUID: &str = "01940000-0000-7000-8000-000000000000";
    const FIXTURE_INVOICE_UUID: &str = "01940000-0000-7000-8000-000000000001";
    const FIXTURE_USER_UUID: &str = "01940000-0000-7000-8000-0000000000ff";

    fn fixture_uuid(s: &str) -> Uuid {
        Uuid::parse_str(s).expect("fixture uuid must parse")
    }

    #[test]
    fn new_generates_prefixed_typeid() {
        let id = new("task").expect("valid prefix");
        assert!(id.starts_with("task_"), "got: {id}");
        // 26-char Crockford base32 suffix.
        assert_eq!(id.len(), "task_".len() + 26);
    }

    #[test]
    fn new_rejects_empty_prefix() {
        let err = new("").unwrap_err();
        assert!(matches!(err, IdError::InvalidPrefix(_)));
    }

    #[test]
    fn new_rejects_uppercase_prefix() {
        let err = new("Task").unwrap_err();
        assert!(matches!(err, IdError::InvalidPrefix(_)));
    }

    #[test]
    fn new_rejects_prefix_with_punctuation() {
        let err = new("task!").unwrap_err();
        assert!(matches!(err, IdError::InvalidPrefix(_)));
    }

    #[test]
    fn parse_round_trips_generated_id() {
        let id = new("invoice").unwrap();
        let parsed = parse(&id).unwrap();
        assert_eq!(parsed.prefix, "invoice");
        assert_eq!(parsed.uuid.get_version_num(), 7);
        // Recompose: prefix_<26-base32> should equal `id`.
        let suffix = TypeIdSuffix::from(parsed.uuid);
        assert_eq!(format!("invoice_{suffix}"), id);
    }

    #[test]
    fn parse_rejects_invalid_suffix() {
        let err = parse("task_not-a-real-typeid").unwrap_err();
        assert!(matches!(err, IdError::InvalidSuffix(_)));
    }

    #[test]
    fn parse_rejects_invalid_prefix() {
        // Uppercase / punctuation prefixes are rejected by upstream.
        let err = parse("Bad_01h455vb4pex5vsknk084sn02q").unwrap_err();
        assert!(matches!(err, IdError::InvalidPrefix(_)), "got {err:?}");
    }

    #[test]
    fn fixtures_round_trip_through_pinned_uuid() {
        for (prefix, uuid_str) in [
            ("task", FIXTURE_TASK_UUID),
            ("invoice", FIXTURE_INVOICE_UUID),
            ("user", FIXTURE_USER_UUID),
        ] {
            let uuid = fixture_uuid(uuid_str);
            let canonical = __test_only_from_uuid(prefix, uuid).unwrap();
            assert!(
                canonical.starts_with(&format!("{prefix}_")),
                "fixture canonical form mismatch: got {canonical}"
            );
            let parsed = parse(&canonical).unwrap();
            assert_eq!(parsed.prefix, prefix);
            assert_eq!(parsed.uuid, uuid);
        }
    }

    // ------------------------------------------------------------------
    // Pinned canonical wire-form fixtures. The expected strings below are
    // the literal output of `mti` v1.1.x for the three pinned UUID inputs;
    // they were captured once by calling `__test_only_from_uuid` and pasted
    // here verbatim. If an upstream change ever shifts the base32 encoding
    // (or anything else in the canonical form) this assertion fails loudly
    // and the cross-language parity matrix must be reviewed.
    // ------------------------------------------------------------------
    const FIXTURE_TASK_CANONICAL: &str = "task_01jg000000e008000000000000";
    const FIXTURE_INVOICE_CANONICAL: &str = "invoice_01jg000000e008000000000001";
    const FIXTURE_USER_CANONICAL: &str = "user_01jg000000e00800000000007z";

    #[test]
    fn fixtures_emit_stable_canonical_strings() {
        let cases = [
            ("task", FIXTURE_TASK_UUID, FIXTURE_TASK_CANONICAL),
            ("invoice", FIXTURE_INVOICE_UUID, FIXTURE_INVOICE_CANONICAL),
            ("user", FIXTURE_USER_UUID, FIXTURE_USER_CANONICAL),
        ];
        for (prefix, uuid_str, expected) in cases {
            let uuid = fixture_uuid(uuid_str);
            let canonical = __test_only_from_uuid(prefix, uuid).unwrap();
            assert_eq!(
                canonical, expected,
                "canonical typeid for ({prefix}, {uuid_str}) drifted from pinned wire form"
            );
            // Round-trip must yield the same UUID bytes.
            let parsed = parse(&canonical).unwrap();
            assert_eq!(parsed.uuid, uuid);
            assert_eq!(parsed.prefix, prefix);
        }
    }

    // ------------------------------------------------------------------
    // Typed<T> + serde
    // ------------------------------------------------------------------
    struct Task;
    impl Prefix for Task {
        const PREFIX: &'static str = "task";
    }

    struct Invoice;
    impl Prefix for Invoice {
        const PREFIX: &'static str = "invoice";
    }

    #[test]
    fn typed_new_wears_marker_prefix() {
        let id: Typed<Task> = Typed::new().unwrap();
        assert!(id.as_str().starts_with("task_"));
    }

    #[test]
    fn typed_parse_accepts_matching_prefix() {
        let id: Typed<Task> = Typed::new().unwrap();
        let s = id.as_str().to_owned();
        let round = Typed::<Task>::parse(&s).unwrap();
        assert_eq!(round, id);
    }

    #[test]
    fn typed_parse_rejects_prefix_mismatch() {
        let id: Typed<Task> = Typed::new().unwrap();
        let err = Typed::<Invoice>::parse(id.as_str()).unwrap_err();
        match err {
            IdError::PrefixMismatch { expected, got } => {
                assert_eq!(expected, "invoice");
                assert_eq!(got, "task");
            }
            other => panic!("expected PrefixMismatch, got {other:?}"),
        }
    }

    #[test]
    fn typed_from_str_delegates_to_parse() {
        let id: Typed<Task> = Typed::new().unwrap();
        let s = id.as_str().to_owned();
        let parsed: Typed<Task> = s.parse().unwrap();
        assert_eq!(parsed, id);
    }

    #[test]
    fn typed_serializes_as_bare_string() {
        let id: Typed<Task> = Typed::new().unwrap();
        let json = serde_json::to_string(&id).unwrap();
        // Bare string form: `"task_..."`. NOT a struct.
        assert!(json.starts_with('"') && json.ends_with('"'));
        assert!(json.contains("task_"));
        assert!(!json.contains('{'));
    }

    #[test]
    fn typed_deserializes_from_bare_string() {
        let id: Typed<Task> = Typed::new().unwrap();
        let json = serde_json::to_string(&id).unwrap();
        let round: Typed<Task> = serde_json::from_str(&json).unwrap();
        assert_eq!(round, id);
    }

    #[test]
    fn typed_deserialize_rejects_wrong_prefix() {
        let id: Typed<Task> = Typed::new().unwrap();
        let json = serde_json::to_string(&id).unwrap();
        let err = serde_json::from_str::<Typed<Invoice>>(&json).unwrap_err();
        assert!(err.to_string().contains("prefix mismatch"), "got: {err}");
    }
}
