# kit init — .githooks/post-pr-open.ps1
#
# Generated by `kit init` per docs/contracts/kit-init-pr-wiring.md
# (sections 2, 3, 5, 6, 8). PowerShell companion to post-pr-open (bash).
# Adopters on native Windows shells run this file; adopters on Linux,
# macOS, or Git-Bash run the .sh counterpart. The two files MUST stay
# behaviorally aligned — port, do not refactor.
#
# When to run: after `gh pr create` (or any equivalent PR-open path)
# succeeds. Invoke directly (`pwsh .githooks/post-pr-open.ps1`) or wire
# into a wrapper. Safe to run multiple times: dedup keys on
# (repo, PR number, event family) and skips when an open follow-up
# already exists in tlc.
#
# What it does:
#   1. Reads PR metadata from `gh pr view` against HEAD.
#   2. Probes ${env:KIT_BUS_INGRESS_URL%/}/healthz with a 5-second
#      timeout (Invoke-WebRequest -TimeoutSec 5).
#   3. Push path: HTTP 2xx within 5s AND $env:KIT_BUS_ENABLED -eq
#      "true" → log + exit 0, no local task.
#   4. Pull path: otherwise → tlc task scheduled "in 10m" with
#      kit:pr-followup + canonical-topic event tag + dedup-key tag.
#
# Fail-open: missing tlc or gh never blocks PR creation; one actionable
# stderr line + exit 0.
#
# Configuration (env, mirrors bash):
#   $env:KIT_BUS_ENABLED         "true" → enable push path probe
#   $env:KIT_BUS_INGRESS_URL     base URL; "/healthz" is appended
#   $env:KIT_POST_PR_HOOK_DEBUG  "1" → trace decisions on stderr
#   $env:KIT_POST_PR_HOOK_FAMILY override event family tag (default: run)
#   $env:KIT_POST_PR_HOOK_DUE    override tlc --due value (default: in 10m)

# Strict-mode parity with bash `set -u`: undefined variables are errors
# even before a typo silently propagates a $null. We do NOT use
# `$ErrorActionPreference = 'Stop'` — each section is responsible for
# its own exit policy and the hook must never propagate a non-zero
# exit upstream (would defeat fail-open).
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

$KitPostPRHookDebug  = if ($env:KIT_POST_PR_HOOK_DEBUG)  { $env:KIT_POST_PR_HOOK_DEBUG }  else { '0' }
$KitPostPRHookFamily = if ($env:KIT_POST_PR_HOOK_FAMILY) { $env:KIT_POST_PR_HOOK_FAMILY } else { 'run' }
$KitPostPRHookDue    = if ($env:KIT_POST_PR_HOOK_DUE)    { $env:KIT_POST_PR_HOOK_DUE }    else { 'in 10m' }

function Write-KitLog {
    param([string]$Message)
    # One-line stderr note. Prefix keeps logs greppable across hooks.
    [Console]::Error.WriteLine("kit: $Message")
}

function Write-KitDebug {
    param([string]$Message)
    if ($KitPostPRHookDebug -ne '1') { return }
    [Console]::Error.WriteLine("kit-debug: $Message")
}

# Map the short event family to the full 4-segment canonical topic name
# expected by bus.ValidateTopic. Mirrors bash kit_canonical_topic. The
# per-event tag carries the full topic so downstream filtering is not
# lossy. Unknown families fall back to "github.pr.<family>" — invalid
# for the bus, but kept distinguishable so adopters see exactly what
# their override produced.
function Get-KitCanonicalTopic {
    param([string]$Family)
    switch ($Family) {
        'run'     { return 'github.pr.run.completed' }
        'comment' { return 'github.pr.comment.created' }
        'merged'  { return 'github.pr.pull.merged' }
        'closed'  { return 'github.pr.pull.closed' }
        default   { return "github.pr.$Family" }
    }
}

# ----- 1. discover gh + read PR metadata --------------------------------------

if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-KitLog 'gh not found on PATH; skipping scheduled follow-up'
    exit 0
}

# `gh pr view` against HEAD picks the PR matching the current branch.
# --json keeps the fields stable across gh versions.
$PRJsonRaw = $null
try {
    $PRJsonRaw = & gh pr view --json number,url,headRefName,headRefOid,title,body,baseRepository 2>$null
} catch {
    $PRJsonRaw = $null
}

if ([string]::IsNullOrWhiteSpace($PRJsonRaw)) {
    Write-KitLog 'no open PR for current branch; skipping scheduled follow-up'
    exit 0
}

# PowerShell parses JSON natively — no sed-based field extraction
# needed. ConvertFrom-Json yields a PSCustomObject we access via dotted
# property names. The .ps1 reads the same fields the bash hook does:
# number, url, headRefName, headRefOid, title, baseRepository.
$PR = $null
try {
    $PR = $PRJsonRaw | ConvertFrom-Json -ErrorAction Stop
} catch {
    Write-KitLog 'could not parse gh pr view JSON; skipping scheduled follow-up'
    exit 0
}

$PRNumber  = $PR.number
$PRUrl     = $PR.url
$PRBranch  = $PR.headRefName
$PRHeadSHA = $PR.headRefOid
$PRTitle   = $PR.title

# baseRepository.{owner.login, name} — degrade to "" when gh omits
# nested fields under older versions.
$PRRepoOwner = ''
$PRRepoName  = ''
if ($PR.PSObject.Properties.Name -contains 'baseRepository' -and $PR.baseRepository) {
    if ($PR.baseRepository.PSObject.Properties.Name -contains 'name') {
        $PRRepoName = $PR.baseRepository.name
    }
    if ($PR.baseRepository.PSObject.Properties.Name -contains 'owner' -and $PR.baseRepository.owner) {
        if ($PR.baseRepository.owner.PSObject.Properties.Name -contains 'login') {
            $PRRepoOwner = $PR.baseRepository.owner.login
        }
    }
}
$PRRepo = ''
if ($PRRepoOwner -and $PRRepoName) {
    $PRRepo = "$PRRepoOwner/$PRRepoName"
}

if (-not $PRNumber) {
    Write-KitLog 'could not parse PR number from gh output; skipping scheduled follow-up'
    exit 0
}

Write-KitDebug "PR #$PRNumber url=$PRUrl branch=$PRBranch head=$PRHeadSHA repo=$PRRepo"

# ----- 2. resolve originating task from branch --------------------------------

# Mirror cmd/kit/init/posthook.go ResolveTaskIDFromBranch:
#   ^[tT]-(\d{3,6})(?:-|$) → "T-NNNN"
$TaskID = ''
if ($PRBranch -match '^[tT]-(\d{3,6})(?:-|$)') {
    $TaskID = "T-$($Matches[1])"
}
Write-KitDebug "task-id from branch: $(if ($TaskID) { $TaskID } else { '<none>' })"

# ----- 3. liveness probe (push path) ------------------------------------------

# Default to pull path; flip to push only when both gating conditions
# resolve true and the probe returns 2xx within 5s.
$UsePush = $false

if ($env:KIT_BUS_ENABLED -eq 'true' -and $env:KIT_BUS_INGRESS_URL) {
    # Strip a trailing slash to match the contract path: ${URL%/}/healthz.
    $ProbeBase = $env:KIT_BUS_INGRESS_URL.TrimEnd('/')
    $ProbeUrl  = "$ProbeBase/healthz"
    Write-KitDebug "probing $ProbeUrl (5s timeout)"

    try {
        # Invoke-WebRequest in 5.1+ honors -TimeoutSec for both connect
        # and total elapsed time. -UseBasicParsing avoids the IE engine
        # on Windows PowerShell (no-op on pwsh 7+, kept for portability).
        $resp = Invoke-WebRequest -Uri $ProbeUrl -TimeoutSec 5 -UseBasicParsing -ErrorAction Stop
        $StatusCode = [int]$resp.StatusCode
        Write-KitDebug "probe status=$StatusCode"
        if ($StatusCode -ge 200 -and $StatusCode -lt 300) {
            $UsePush = $true
        }
    } catch {
        # Timeout, DNS error, TLS error, non-2xx — degrade to pull path.
        # We deliberately do NOT inspect the exception type; any error
        # flips us to pull, matching the bash hook's curl-fails-fall-
        # through semantics.
        Write-KitDebug "probe failed: $($_.Exception.Message)"
    }
}

if ($UsePush) {
    Write-KitLog 'bus ingress healthy, deferring follow-up to host listener'
    exit 0
}

# ----- 4. pull path: schedule tlc follow-up -----------------------------------

if (-not (Get-Command tlc -ErrorAction SilentlyContinue)) {
    Write-KitLog "tlc not found on PATH; skipping scheduled follow-up for PR #$PRNumber"
    exit 0
}

# Duplicate-prevention key: (repo, PR number, event family). Encoded as
# a per-triple tag so tlc's --tag filter resolves the lookup in one call.
# Strip slashes from repo so the tag stays opaque to tlc's tag parser.
$RepoTag  = ($PRRepo -replace '/', '-')
$DedupTag = "kit:pr-followup:${RepoTag}:${PRNumber}:${KitPostPRHookFamily}"

# tlc task list filters by tag; if any open (TODO/in_progress) task
# matches, we treat the follow-up as already scheduled and skip.
$Existing = ''
try {
    $Existing = & tlc task list `
        --tag $DedupTag `
        --status TODO `
        --status in_progress `
        --format json 2>$null
    if ($null -eq $Existing) { $Existing = '' }
    if ($Existing -is [array]) { $Existing = $Existing -join "`n" }
} catch {
    $Existing = ''
}

if ($Existing -and $Existing -ne '[]' -and $Existing -ne 'null') {
    # Heuristic: any non-empty JSON array containing an "id" field means
    # an open follow-up exists. We do not parse further — the dedup tag
    # itself encodes the triple and tlc enforces status filtering.
    if ($Existing -match '"id"') {
        Write-KitLog "follow-up already scheduled for PR #${PRNumber} (${KitPostPRHookFamily}); skipping"
        exit 0
    }
}

# Build the create command. tlc --due accepts natural-language ("in 10m")
# and absolute forms; we pass-through whatever KIT_POST_PR_HOOK_DUE
# resolves to (default: "in 10m").
$CanonicalTopic  = Get-KitCanonicalTopic -Family $KitPostPRHookFamily
$TaskTitle       = "Review PR #${PRNumber}: ${PRTitle}"
$TaskDescription = @"
Auto-scheduled by kit post-pr-open hook.

PR:        $PRUrl
PR #:      $PRNumber
Branch:    $PRBranch
Head SHA:  $PRHeadSHA
Repo:      $PRRepo
Family:    $KitPostPRHookFamily
Trigger:   $CanonicalTopic
Task link: $TaskID
"@

# Compose tlc args. --tag is repeatable; we pass all three (the fixed
# kit:pr-followup, the per-event canonical tag carrying the full
# 4-segment topic, and the dedup-key tag whose family segment stays
# as the short label).
$TLCArgs = @(
    'task', 'create', $TaskTitle,
    '--description', $TaskDescription,
    '--due', $KitPostPRHookDue,
    '--tag', 'kit:pr-followup',
    '--tag', "event:$CanonicalTopic",
    '--tag', $DedupTag
)

if ($TaskID) {
    # tlc resolves --reference against the configured track index.
    $TLCArgs += @('--reference', $TaskID)
}

$tlcOk = $true
try {
    & tlc @TLCArgs *> $null
    if ($LASTEXITCODE -ne 0) { $tlcOk = $false }
} catch {
    $tlcOk = $false
}

if (-not $tlcOk) {
    # tlc failures must not block PR creation — log + exit 0.
    Write-KitLog "tlc task create failed for PR #${PRNumber}; check 'tlc doctor' or rerun manually"
    exit 0
}

Write-KitLog "scheduled tlc follow-up for PR #${PRNumber} (${KitPostPRHookFamily}, due ${KitPostPRHookDue})"
exit 0
