#!/usr/bin/env bash
# Generated by kit init. Refresh with `kit init` (non-destructive: refreshes
# in place when the on-disk SHA matches .kit/generated.json, else writes a
# .kit-suggested sibling). Do not hand-edit unless you also bump the manifest
# hash, or your edit will surface as a .kit-suggested sibling on the next run.
#
# Contract: docs/contracts/kit-init-pr-wiring.md sections 4, 6, 7.
#
# Exit semantics:
#   0  all gates pass
#   1  lint gate failed
#   2  test gate failed
#   3  scratchpad cleanup gate failed (ephemeral planning artefacts found)
#
# Bypass: standard `git --no-verify` (e.g. `git push --no-verify`).

set -u

# --- gate 1+2: lint, test ----------------------------------------------------
#
# Resolution order per gate (independent — gate 1 may resolve via Makefile and
# gate 2 via .kit/pre-pr.toml):
#   1. Makefile target
#   2. mise task
#   3. .kit/pre-pr.toml field
#   4. no gate declared (single-line stderr note, continue)

repo_root() {
    git rev-parse --show-toplevel 2>/dev/null || pwd
}

has_make_target() {
    # $1 = target name. Returns 0 iff `make -n <target>` parses Makefile and
    # finds the target. Suppresses output so callers stay quiet.
    [ -f "$(repo_root)/Makefile" ] || return 1
    ( cd "$(repo_root)" && make -n "$1" >/dev/null 2>&1 )
}

has_mise_task() {
    # $1 = task name. mise tasks live under [tasks.<name>] in mise.toml or
    # .mise.toml. We grep both files because mise's own tasks-list subcommand
    # would shell out to mise which may not be on PATH at hook resolve time.
    local root file
    root="$(repo_root)"
    for file in "$root/mise.toml" "$root/.mise.toml"; do
        [ -f "$file" ] || continue
        grep -qE "^\[tasks\.$1\]" "$file" && return 0
    done
    return 1
}

kit_toml_field() {
    # $1 = field name (lint or test). Echoes the field value, or empty if
    # absent.
    #
    # Supported subset: top-level scalar `<field> = "value"` or
    # `<field> = 'value'`, with optional surrounding whitespace and an
    # optional trailing `# comment`. Both quote styles map to the same
    # literal string (we deliberately do not implement TOML's escape
    # processing for "..." — adopters who need that can wire a Makefile
    # target instead).
    local file value
    file="$(repo_root)/.kit/pre-pr.toml"
    [ -f "$file" ] || return 0
    # First sed: extract content between either quote style. Two
    # alternatives keep the expression POSIX-portable (sed -E lacks
    # alternation grouping on BSD sed in some versions, but two
    # separate `s///p` rules are fine).
    value="$(sed -n -E \
        -e "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*\"([^\"]*)\".*$/\1/p" \
        -e "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*'([^']*)'.*$/\1/p" \
        "$file" | head -n1)"
    printf '%s' "$value"
}

run_gate() {
    # $1 = gate name (lint|test). Resolves and invokes the command for this
    # gate per the documented order. Returns the gate exit code.
    local gate="$1"
    if has_make_target "$gate"; then
        ( cd "$(repo_root)" && make "$gate" )
        return $?
    fi
    if has_mise_task "$gate"; then
        ( cd "$(repo_root)" && mise run "$gate" )
        return $?
    fi
    local cmd
    cmd="$(kit_toml_field "$gate")"
    if [ -n "$cmd" ]; then
        ( cd "$(repo_root)" && sh -c "$cmd" )
        return $?
    fi
    echo "kit: no $gate gate declared; skipping" >&2
    return 0
}

# --- gate 3: scratchpad cleanup ----------------------------------------------
#
# Scan tracked files for ephemeral planning markers. Any hit fails the hook;
# the author is expected to either delete the marker (it was incidental) or
# move the surrounding note to the per-user scratchpad (Section 4 location).
#
# Patterns (case-sensitive, line-anchored to a comment lead-in):
#   SCRATCH:        — temporary planning note
#   FIXME-PLAN:     — TODO that belongs in a plan, not the source tree
#   AGENT-NOTE:     — agent thought-dump
#   KIT-SCRATCH:    — explicit kit-init scratchpad marker
#
# Detection runs against `git ls-files`, then filters out:
#   - this hook itself (.githooks/pre-pr)
#   - the contract docs that document the patterns
# so the hook doesn't false-positive on its own definition.

SCRATCH_PATTERNS_RE='(SCRATCH|FIXME-PLAN|AGENT-NOTE|KIT-SCRATCH):'

scan_scratchpad() {
    local root
    root="$(repo_root)"
    # -H forces filename in output even for single-file inputs (BSD grep
    # otherwise omits the prefix and xargs may batch one file at a time).
    ( cd "$root" && git ls-files -z 2>/dev/null \
        | xargs -0 grep -HnE "$SCRATCH_PATTERNS_RE" 2>/dev/null \
        | grep -vE '^\.githooks/pre-pr:' \
        | grep -vE '^docs/contracts/kit-init-pr-wiring\.md:' \
        | grep -vE '^cmd/kit/init/prepr_assets/pre-pr\.sh:' \
        | grep -vE '^cmd/kit/init/prepr\.go:' \
        | grep -vE '^cmd/kit/init/prepr_test\.go:' \
        || true )
}

# project_id slug — derived per Section 4 of the contract.
project_id() {
    local origin slug
    origin="$(git -C "$(repo_root)" config --get remote.origin.url 2>/dev/null || true)"
    if [ -n "$origin" ]; then
        slug="$origin"
        # Strip leading git@host: or scheme://user@host[:port]/.
        slug="${slug#git@}"
        slug="${slug#*://}"
        slug="${slug#*@}"
        slug="${slug%.git}"
        slug=$(printf '%s' "$slug" | tr ':' '/')
    else
        slug="$(repo_root)"
    fi
    # lowercase, non-[a-z0-9-] → -, collapse runs, trim.
    slug=$(printf '%s' "$slug" \
        | tr '[:upper:]' '[:lower:]' \
        | sed -E 's/[^a-z0-9-]+/-/g' \
        | sed -E 's/-+/-/g' \
        | sed -E 's/^-+//; s/-+$//')
    if [ -z "$slug" ]; then
        slug="kit-init"
    fi
    printf '%s' "$slug"
}

scratchpad_path() {
    local id="$1" base
    case "$(uname -s)" in
        Darwin)
            base="${TMPDIR:-/tmp}"
            ;;
        Linux)
            if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
                base="$XDG_RUNTIME_DIR"
            elif [ -n "${TMPDIR:-}" ]; then
                base="$TMPDIR"
            else
                base="/tmp"
            fi
            ;;
        *)
            base="${TMPDIR:-/tmp}"
            ;;
    esac
    # strip trailing slash
    base="${base%/}"
    printf '%s/%s.scratchpad' "$base" "$id"
}

# --- run gates ---------------------------------------------------------------

echo "kit: pre-pr gates" >&2

run_gate lint
lint_rc=$?
if [ $lint_rc -ne 0 ]; then
    echo "kit: pre-pr lint failed (exit $lint_rc)" >&2
    exit 1
fi

run_gate test
test_rc=$?
if [ $test_rc -ne 0 ]; then
    echo "kit: pre-pr test failed (exit $test_rc)" >&2
    exit 2
fi

hits="$(scan_scratchpad)"
if [ -n "$hits" ]; then
    id="$(project_id)"
    pad="$(scratchpad_path "$id")"
    echo "kit: pre-pr scratchpad gate failed; ephemeral planning artefacts in tracked files:" >&2
    printf '%s\n' "$hits" >&2
    echo "" >&2
    echo "kit: move the surrounding notes to $pad and remove the markers, then re-run." >&2
    exit 3
fi

exit 0
