# Generated by kit init. Refresh with `kit init` (non-destructive: refreshes
# in place when the on-disk SHA matches .kit/generated.json, else writes a
# .kit-suggested sibling). Do not hand-edit unless you also bump the manifest
# hash, or your edit will surface as a .kit-suggested sibling on the next run.
#
# Contract: docs/contracts/kit-init-pr-wiring.md sections 4, 6, 7.
#
# Exit semantics (mirror pre-pr.sh):
#   0  all gates pass
#   1  lint gate failed
#   2  test gate failed
#   3  scratchpad cleanup gate failed (ephemeral planning artefacts found)
#
# Bypass: standard `git --no-verify` (e.g. `git push --no-verify`).
#
# Use this file from PowerShell / cmd.exe on native Windows. The bash
# companion (pre-pr) covers Git Bash / MSYS / Cygwin / WSL adopters.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

# --- helpers -----------------------------------------------------------

function Get-RepoRoot {
    $top = (& git rev-parse --show-toplevel 2>$null)
    if ($LASTEXITCODE -eq 0 -and $top) { return $top.Trim() }
    return (Get-Location).Path
}

function Test-MakeTarget {
    param([string]$Target)
    $root = Get-RepoRoot
    $makefile = Join-Path $root 'Makefile'
    if (-not (Test-Path $makefile)) { return $false }
    # `make -n` is the same probe the bash hook uses. We allow either
    # GNU make on PATH (rare on Windows) or fall through to silent false
    # when make is absent — adopters who declare make targets typically
    # also install make.
    if (-not (Get-Command make -ErrorAction SilentlyContinue)) { return $false }
    Push-Location $root
    try {
        & make -n $Target 2>$null 1>$null
        return ($LASTEXITCODE -eq 0)
    } finally {
        Pop-Location
    }
}

function Test-MiseTask {
    param([string]$Task)
    $root = Get-RepoRoot
    foreach ($name in @('mise.toml', '.mise.toml')) {
        $file = Join-Path $root $name
        if (-not (Test-Path $file)) { continue }
        if (Select-String -Path $file -Pattern ("^\[tasks\." + [Regex]::Escape($Task) + "\]") -Quiet) {
            return $true
        }
    }
    return $false
}

function Get-KitTomlField {
    # Mirrors kit_toml_field in pre-pr.sh: accept either quote style and
    # tolerate trailing whitespace / # comment after the closing quote.
    param([string]$Field)
    $root = Get-RepoRoot
    $file = Join-Path $root '.kit/pre-pr.toml'
    if (-not (Test-Path $file)) { return '' }
    $escaped = [Regex]::Escape($Field)
    foreach ($line in Get-Content $file) {
        $m = [Regex]::Match($line, "^\s*$escaped\s*=\s*""([^""]*)"".*$")
        if ($m.Success) { return $m.Groups[1].Value }
        $m = [Regex]::Match($line, "^\s*$escaped\s*=\s*'([^']*)'.*$")
        if ($m.Success) { return $m.Groups[1].Value }
    }
    return ''
}

function Invoke-Gate {
    param([string]$Gate)
    $root = Get-RepoRoot
    if (Test-MakeTarget $Gate) {
        Push-Location $root
        try { & make $Gate; return $LASTEXITCODE }
        finally { Pop-Location }
    }
    if (Test-MiseTask $Gate) {
        Push-Location $root
        try { & mise run $Gate; return $LASTEXITCODE }
        finally { Pop-Location }
    }
    $cmd = Get-KitTomlField $Gate
    if ($cmd) {
        Push-Location $root
        try {
            # cmd is a shell command; route through cmd.exe /c so it
            # matches the bash hook's `sh -c "$cmd"` semantics (free-form
            # one-liner). Adopters who need PowerShell semantics can
            # wire a Makefile/mise task instead.
            & cmd.exe /c $cmd
            return $LASTEXITCODE
        } finally { Pop-Location }
    }
    [Console]::Error.WriteLine("kit: no $Gate gate declared; skipping")
    return 0
}

# --- scratchpad detection ---------------------------------------------

# Mirror SCRATCH_PATTERNS_RE in pre-pr.sh. Keep markers in lock-step
# with ScratchpadPatterns in cmd/kit/init/prepr.go.
# Markers: SCRATCH: FIXME-PLAN: AGENT-NOTE: KIT-SCRATCH:
$ScratchPatternsRe = '(SCRATCH|FIXME-PLAN|AGENT-NOTE|KIT-SCRATCH):'

function Find-Scratchpad {
    $root = Get-RepoRoot
    Push-Location $root
    try {
        $files = & git ls-files 2>$null
        if ($LASTEXITCODE -ne 0) { return @() }
        $hits = @()
        foreach ($f in $files) {
            if (-not (Test-Path $f)) { continue }
            # Skip the same exclusions as the bash hook so the hook
            # doesn't false-positive on its own definition / docs.
            if ($f -eq '.githooks/pre-pr') { continue }
            if ($f -eq '.githooks/pre-pr.ps1') { continue }
            if ($f -eq 'docs/contracts/kit-init-pr-wiring.md') { continue }
            if ($f -eq 'cmd/kit/init/prepr_assets/pre-pr.sh') { continue }
            if ($f -eq 'cmd/kit/init/prepr_assets/pre-pr.ps1') { continue }
            if ($f -eq 'cmd/kit/init/prepr.go') { continue }
            if ($f -eq 'cmd/kit/init/prepr_test.go') { continue }
            $found = Select-String -Path $f -Pattern $ScratchPatternsRe `
                -CaseSensitive -ErrorAction SilentlyContinue
            if ($found) {
                foreach ($h in $found) {
                    $hits += ('{0}:{1}:{2}' -f $f, $h.LineNumber, $h.Line.Trim())
                }
            }
        }
        return $hits
    } finally {
        Pop-Location
    }
}

# --- project_id slug (Section 4) --------------------------------------

function Get-ProjectId {
    $root = Get-RepoRoot
    $origin = & git -C $root config --get remote.origin.url 2>$null
    if ($LASTEXITCODE -ne 0) { $origin = '' }
    if ($origin) {
        $slug = $origin.Trim()
        # Strip git@host: shorthand.
        $slug = $slug -replace '^git@', ''
        # Strip scheme://[user@]host[:port]/.
        if ($slug -match '^[^:]+://') {
            $slug = $slug -replace '^[^:]+://', ''
            $slug = $slug -replace '^[^@]+@', ''
        }
        $slug = $slug -replace '\.git$', ''
        $slug = $slug -replace ':', '/'
    } else {
        $slug = $root
    }
    $slug = $slug.ToLower()
    $slug = ($slug -replace '[^a-z0-9-]+', '-')
    $slug = ($slug -replace '-+', '-')
    $slug = $slug.Trim('-')
    if (-not $slug) { $slug = 'kit-init' }
    return $slug
}

function Get-ScratchpadPath {
    param([string]$Id)
    # Mirror Go-side ScratchpadPath Windows precedence:
    #   LOCALAPPDATA + \Temp, else TEMP (no extra \Temp), else
    #   TMPDIR, else /tmp. Windows-native paths use \, so we join
    #   with Join-Path rather than emit POSIX slashes here.
    if ($env:LOCALAPPDATA) {
        $base = Join-Path $env:LOCALAPPDATA 'Temp'
    } elseif ($env:TEMP) {
        $base = $env:TEMP
    } elseif ($env:TMPDIR) {
        $base = $env:TMPDIR
    } else {
        $base = '/tmp'
    }
    return (Join-Path $base ($Id + '.scratchpad'))
}

# --- run gates --------------------------------------------------------

[Console]::Error.WriteLine('kit: pre-pr gates')

$lintRc = Invoke-Gate 'lint'
if ($lintRc -ne 0) {
    [Console]::Error.WriteLine("kit: pre-pr lint failed (exit $lintRc)")
    exit 1
}

$testRc = Invoke-Gate 'test'
if ($testRc -ne 0) {
    [Console]::Error.WriteLine("kit: pre-pr test failed (exit $testRc)")
    exit 2
}

$hits = Find-Scratchpad
if ($hits.Count -gt 0) {
    $id = Get-ProjectId
    $pad = Get-ScratchpadPath $id
    [Console]::Error.WriteLine(
        'kit: pre-pr scratchpad gate failed; ephemeral planning artefacts in tracked files:')
    foreach ($h in $hits) { [Console]::Error.WriteLine($h) }
    [Console]::Error.WriteLine('')
    [Console]::Error.WriteLine(
        "kit: move the surrounding notes to $pad and remove the markers, then re-run.")
    exit 3
}

exit 0
