// Generator for the four .github/workflows/kit-bus-*.yml files. The
// output is byte-deterministic given the same inputs (no time-of-day,
// no random IDs) so generated.json hash comparisons stay stable across
// re-runs.
//
// Each workflow is constructed from a small in-memory template; we
// avoid yaml.Marshal because GitHub Actions YAML is order-sensitive in
// places (`on:` keys must appear before `jobs:` in the canonical
// rendering, comment annotations on top read as section headers in the
// repo UI). Plain string interpolation gives us full control without
// pulling a heavy YAML library along for the ride.
package buswf

import (
	"fmt"
	"sort"
)

// File is a single rendered workflow file destined for
// `.github/workflows/<Name>`. Body holds the byte-exact YAML.
type File struct {
	Name  string // relative filename, e.g. kit-bus-pr-run-completed.yml
	Body  []byte // canonical YAML body (deterministic)
	Topic string // the bus topic this workflow emits
}

// Files returns the four kit-bus workflow files in the order:
//  1. run.completed
//  2. comment.created
//  3. pull.merged
//  4. pull.closed
//
// Order is stable so callers iterating Files get a deterministic
// generated.json manifest entry sequence.
func Files() []File {
	return []File{
		runCompletedFile(),
		commentCreatedFile(),
		pullMergedFile(),
		pullClosedFile(),
	}
}

// FileByTopic returns the File for the given topic, or false if the
// topic is not one of the four canonical PR-lifecycle topics.
func FileByTopic(topic string) (File, bool) {
	for _, f := range Files() {
		if f.Topic == topic {
			return f, true
		}
	}
	return File{}, false
}

// Filenames returns the workflow filenames in canonical order. Used by
// callers (init flow) that just need the path list without bodies.
func Filenames() []string {
	out := []string{}
	for _, f := range Files() {
		out = append(out, f.Name)
	}
	sort.Strings(out) // alphabetical for manifest stability
	return out
}

// commonHeader returns the YAML header common to every kit-bus
// workflow: name, comment block explaining the file's provenance and
// the runtime gating expression. Concrete `on:` and `jobs:` are
// appended by per-topic builders below.
//
// `name` is the workflow's display name (without the `kit-bus: ` prefix);
// the prefix is added here.
func commonHeader(displayName, topic string) string {
	return "" +
		"# Generated by kit init (T-0776). Edit with care — kit re-runs may\n" +
		"# suggest a .kit-suggested sibling if this file diverges from the\n" +
		"# manifest hash. Owner contract:\n" +
		"#   docs/contracts/kit-init-pr-wiring.md (sections 2, 3, 6).\n" +
		"#\n" +
		fmt.Sprintf("# Emits bus topic: %s\n", topic) +
		"#\n" +
		"# Runtime-disabled unless BOTH of these are set at the repo or\n" +
		"# org level:\n" +
		"#   vars.KIT_BUS_ENABLED       == \"true\"\n" +
		"#   vars.KIT_BUS_INGRESS_URL   non-empty\n" +
		// Wrap in quotes because the value contains ':' which YAML
		// parsers (correctly) read as a mapping continuation.
		fmt.Sprintf("name: \"kit-bus: %s\"\n\n", displayName)
}

// emitJob renders the common emit-bus job. extraEnv is appended to the
// step env block so per-topic payload context (run id, comment id,
// merge sha, etc.) is available to the helper binary.
//
// kitBusVersion is pinned to the kit module ref; tests overwrite via
// the env var KIT_BUS_EMIT_REF to point at a local build during dev.
// At generation time we hard-code "latest" — the workflow uses
// `go install hop.top/kit/cmd/kit-bus-emit@latest` so consumers stay
// on the published binary unless they pin via repo policy.
func emitJob(topic string, eventTrigger string, ifGuards []string, extraEnv map[string]string, payloadFlags []string) string {
	// Combine the base gating expression with any per-trigger guards
	// (e.g. `&& github.event.pull_request.merged == true`).
	base := "vars.KIT_BUS_ENABLED == 'true' && vars.KIT_BUS_INGRESS_URL != ''"
	if len(ifGuards) > 0 {
		for _, g := range ifGuards {
			base = base + " && " + g
		}
	}

	envBlock := "" +
		"        env:\n" +
		"          KIT_BUS_INGRESS_URL: ${{ vars.KIT_BUS_INGRESS_URL }}\n" +
		"          KIT_BUS_TOKEN: ${{ secrets.KIT_BUS_TOKEN }}\n" +
		"          KIT_BUS_SIGNING_KEY: ${{ secrets.KIT_BUS_SIGNING_KEY }}\n" +
		"          KIT_BUS_STRICT: ${{ vars.KIT_BUS_STRICT }}\n" +
		fmt.Sprintf("          KIT_BUS_TOPIC: %s\n", topic) +
		"          KIT_BUS_REPO: ${{ github.repository }}\n" +
		"          KIT_BUS_ACTOR: ${{ github.actor }}\n"

	// Sort extra env keys so output is deterministic.
	keys := make([]string, 0, len(extraEnv))
	for k := range extraEnv {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		envBlock += fmt.Sprintf("          %s: %s\n", k, extraEnv[k])
	}

	// Build `kit-bus-emit` invocation. Flags listed by caller. We rely
	// on the helper binary for size truncation, signature, and
	// fail-open vs fail-closed semantics.
	runBlock := "        run: |\n" +
		"          set -eu\n" +
		"          go install hop.top/kit/cmd/kit-bus-emit@latest\n" +
		"          \"$(go env GOPATH)/bin/kit-bus-emit\""
	for _, fl := range payloadFlags {
		runBlock += " \\\n            " + fl
	}
	runBlock += "\n"

	return "" +
		"jobs:\n" +
		"  emit-bus:\n" +
		fmt.Sprintf("    if: ${{ %s }}\n", base) +
		"    runs-on: ubuntu-latest\n" +
		"    steps:\n" +
		"      - name: install go (for kit-bus-emit)\n" +
		"        uses: actions/setup-go@v5\n" +
		"        with:\n" +
		"          go-version: \"stable\"\n" +
		fmt.Sprintf("      - name: emit %s\n", topic) +
		envBlock +
		runBlock
}

// Helpers that build each of the four files. The factoring keeps each
// concrete workflow short and obvious; shared structure lives in
// commonHeader + emitJob.

func runCompletedFile() File {
	topic := string(TopicRunCompleted)
	header := commonHeader("pr run completed", topic)
	on := "" +
		"on:\n" +
		"  workflow_run:\n" +
		"    workflows: [\"*\"]\n" +
		"    types: [completed]\n\n"

	extraEnv := map[string]string{
		"KIT_BUS_RUN_ID":         "${{ github.event.workflow_run.id }}",
		"KIT_BUS_RUN_NAME":       "${{ github.event.workflow_run.name }}",
		"KIT_BUS_RUN_CONCLUSION": "${{ github.event.workflow_run.conclusion }}",
		"KIT_BUS_RUN_URL":        "${{ github.event.workflow_run.html_url }}",
		"KIT_BUS_RUN_LOGS_URL":   "${{ github.event.workflow_run.logs_url }}",
		"KIT_BUS_PR_NUMBER":      "${{ github.event.workflow_run.pull_requests[0].number }}",
		"KIT_BUS_PR_URL":         "${{ github.event.workflow_run.pull_requests[0].url }}",
		"KIT_BUS_PR_BRANCH":      "${{ github.event.workflow_run.head_branch }}",
		"KIT_BUS_PR_HEAD_SHA":    "${{ github.event.workflow_run.head_sha }}",
		"KIT_BUS_PR_BASE_SHA":    "${{ github.event.workflow_run.head_repository.default_branch }}",
	}
	flags := []string{
		"--kind run.completed",
	}
	body := header + on + emitJob(topic, "workflow_run", nil, extraEnv, flags)
	return File{Name: "kit-bus-pr-run-completed.yml", Body: []byte(body), Topic: topic}
}

func commentCreatedFile() File {
	topic := string(TopicCommentCreated)
	header := commonHeader("pr comment created", topic)
	on := "" +
		"on:\n" +
		"  pull_request_review_comment:\n" +
		"    types: [created]\n\n"

	extraEnv := map[string]string{
		"KIT_BUS_COMMENT_ID":     "${{ github.event.comment.id }}",
		"KIT_BUS_COMMENT_AUTHOR": "${{ github.event.comment.user.login }}",
		"KIT_BUS_COMMENT_URL":    "${{ github.event.comment.html_url }}",
		"KIT_BUS_COMMENT_BODY":   "${{ github.event.comment.body }}",
		"KIT_BUS_PR_NUMBER":      "${{ github.event.pull_request.number }}",
		"KIT_BUS_PR_URL":         "${{ github.event.pull_request.html_url }}",
		"KIT_BUS_PR_BRANCH":      "${{ github.event.pull_request.head.ref }}",
		"KIT_BUS_PR_HEAD_SHA":    "${{ github.event.pull_request.head.sha }}",
		"KIT_BUS_PR_BASE_SHA":    "${{ github.event.pull_request.base.sha }}",
	}
	flags := []string{
		"--kind comment.created",
	}
	body := header + on + emitJob(topic, "pull_request_review_comment", nil, extraEnv, flags)
	return File{Name: "kit-bus-pr-comment-created.yml", Body: []byte(body), Topic: topic}
}

func pullMergedFile() File {
	topic := string(TopicPullMerged)
	header := commonHeader("pr pull merged", topic)
	on := "" +
		"on:\n" +
		"  pull_request:\n" +
		"    types: [closed]\n\n"

	extraEnv := map[string]string{
		"KIT_BUS_MERGE_COMMIT_SHA": "${{ github.event.pull_request.merge_commit_sha }}",
		"KIT_BUS_MERGED_AT":        "${{ github.event.pull_request.merged_at }}",
		"KIT_BUS_PR_NUMBER":        "${{ github.event.pull_request.number }}",
		"KIT_BUS_PR_URL":           "${{ github.event.pull_request.html_url }}",
		"KIT_BUS_PR_BRANCH":        "${{ github.event.pull_request.head.ref }}",
		"KIT_BUS_PR_HEAD_SHA":      "${{ github.event.pull_request.head.sha }}",
		"KIT_BUS_PR_BASE_SHA":      "${{ github.event.pull_request.base.sha }}",
	}
	flags := []string{
		"--kind pull.merged",
	}
	guards := []string{"github.event.pull_request.merged == true"}
	body := header + on + emitJob(topic, "pull_request", guards, extraEnv, flags)
	return File{Name: "kit-bus-pr-pull-merged.yml", Body: []byte(body), Topic: topic}
}

func pullClosedFile() File {
	topic := string(TopicPullClosed)
	header := commonHeader("pr pull closed", topic)
	on := "" +
		"on:\n" +
		"  pull_request:\n" +
		"    types: [closed]\n\n"

	extraEnv := map[string]string{
		"KIT_BUS_CLOSED_AT":   "${{ github.event.pull_request.closed_at }}",
		"KIT_BUS_REASON":      "${{ github.event.pull_request.state_reason }}",
		"KIT_BUS_PR_NUMBER":   "${{ github.event.pull_request.number }}",
		"KIT_BUS_PR_URL":      "${{ github.event.pull_request.html_url }}",
		"KIT_BUS_PR_BRANCH":   "${{ github.event.pull_request.head.ref }}",
		"KIT_BUS_PR_HEAD_SHA": "${{ github.event.pull_request.head.sha }}",
		"KIT_BUS_PR_BASE_SHA": "${{ github.event.pull_request.base.sha }}",
	}
	flags := []string{
		"--kind pull.closed",
	}
	// Symmetric to pull.merged: the close-without-merge half of the
	// closed event.
	guards := []string{"github.event.pull_request.merged == false"}
	body := header + on + emitJob(topic, "pull_request", guards, extraEnv, flags)
	return File{Name: "kit-bus-pr-pull-closed.yml", Body: []byte(body), Topic: topic}
}
