"""Byte-exact conformance against the shared cross-language wire fixtures.

``sdk/tests/cross-lang/fixtures/mcp-wire.json`` is the parity contract for
all four MCP ports. It was generated by driving the Go surface over real
HTTP and capturing response bytes, so it is byte-identical to Go by
construction rather than by transcription.

"Byte-exact" is meant literally: each case's response is compared as
bytes, with no JSON decode/re-encode step on either side. Go sorts object
keys lexicographically, emits struct fields in declaration order, escapes
``<``/``>``/``&``, and appends a trailing newline; a port whose serialiser
differs has to reorder to match, not normalise the comparison away.

The fixture file also carries the command trees the cases were captured
against. Both are rebuilt here, because two cases differ only by which
tree served them.

One section is deliberately not byte-exact end to end. ``mrtr`` replays
the confirmation loop, whose first round mints a fresh, time-bound
``requestState`` carrying a MAC that differs on every run: only its
framing is checkable there. The second round echoes that state back and
is compared byte-exact like everything else, which is what makes the
exchange verifiable rather than merely plausible.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from hop_top_kit.mcp import (
    Bridge,
    Command,
    Flag,
    Headers,
    Request,
    Result,
    mount_mcp,
)

FIXTURE = (
    Path(__file__).resolve().parents[2] / "tests" / "cross-lang" / "fixtures" / "mcp-wire.json"
)


def load_fixture() -> dict[str, Any]:
    """Read the fixture document.

    A missing fixture is a hard failure, not a skip: this suite exists to
    prove parity, and a silently-skipped parity suite is worse than no
    suite at all.
    """
    if not FIXTURE.exists():  # pragma: no cover - fixture ships with the repo
        raise FileNotFoundError(f"wire fixture not found at {FIXTURE}")
    return json.loads(FIXTURE.read_text())


FIXTURE_DOC = load_fixture()

#: Independent request/response pairs, each replayed against a FRESH handler.
CASES: list[dict[str, Any]] = FIXTURE_DOC["cases"]

#: Ordered step lists, each replayed against ONE long-lived handler. These
#: exist because some surface behaviour is only observable across requests:
#: per-case isolation hides it, and adopters serve from persistent
#: processes where it is the normal condition.
SEQUENCES: list[dict[str, Any]] = FIXTURE_DOC.get("sequences", [])


# --- the two command trees the fixtures were captured against -------------


def legacy_tree() -> Command:
    """The tree behind every ``legacy/*`` case.

    ``widget add`` carries the full flag set including a hidden and a
    deprecated flag, both of which must be absent from the emitted
    schema.
    """
    return Command(
        name="root",
        children=[
            Command(
                name="widget",
                children=[
                    Command(
                        name="add",
                        short="Add a widget",
                        run=lambda flags: Result(stdout="added\n"),
                        annotations={"kit/side-effect": "write"},
                        flags=[
                            Flag("name", "widget name", "string", required=True),
                            Flag("count", "widget count", "int"),
                            Flag("force", "force flag", "bool"),
                            Flag("tag", "tag list", "stringSlice"),
                            Flag("hidden-flag", "should be hidden", "string", hidden=True),
                            Flag(
                                "deprecated-flag",
                                "should be dropped",
                                "string",
                                deprecated=True,
                            ),
                        ],
                    ),
                    Command(
                        name="delete",
                        short="Delete a widget",
                        run=lambda flags: Result(stdout="deleted\n"),
                        annotations={"kit/side-effect": "destructive"},
                    ),
                ],
            ),
            Command(
                name="secret",
                short="Locked",
                run=lambda flags: Result(),
                annotations={"kit/auth-required": "true"},
            ),
            Command(
                name="deploy",
                short="Deploy",
                run=lambda flags: Result(),
                annotations={"kit/requires-confirmation": "true"},
            ),
            Command(
                name="ping",
                short="Ping the server",
                run=lambda flags: Result(stdout="pong\n"),
                annotations={"kit/side-effect": "read"},
            ),
        ],
    )


def modern_tree() -> Command:
    """The tree behind every ``modern/*`` case.

    Deliberately not the legacy tree: ``widget add`` here declares only
    ``name`` and ``count``, and the fixture's modern ``tools/list``
    response pins exactly that narrower schema.
    """
    return Command(
        name="root",
        children=[
            Command(
                name="ping",
                short="Ping the server",
                run=lambda flags: Result(stdout="pong\n"),
                annotations={"kit/side-effect": "read"},
            ),
            Command(
                name="widget",
                children=[
                    Command(
                        name="add",
                        short="Add a widget",
                        run=lambda flags: Result(stdout="added\n"),
                        annotations={"kit/side-effect": "write"},
                        flags=[
                            Flag("name", "widget name", "string", required=True),
                            Flag("count", "widget count", "int"),
                        ],
                    ),
                    Command(
                        name="delete",
                        short="Delete a widget",
                        run=lambda flags: Result(stdout="deleted\n"),
                        annotations={"kit/side-effect": "destructive"},
                    ),
                ],
            ),
            Command(
                name="secret",
                short="Locked",
                run=lambda flags: Result(),
                annotations={"kit/auth-required": "true"},
            ),
            Command(
                name="deploy",
                short="Deploy",
                run=lambda flags: Result(),
                annotations={"kit/requires-confirmation": "true"},
            ),
        ],
    )


def surface_for(case: dict[str, Any]):
    """Build a FRESH surface for one case.

    Fresh per case, deliberately. Every entry under ``cases`` is a
    self-contained request/response pair that must not depend on any
    other having run first, so each gets a handler that has served
    nothing else.

    That isolation is also what made a real property invisible for a
    while, which is why ``sequences`` exists alongside: see
    :func:`test_wire_sequence_is_byte_exact`.
    """
    tree = legacy_tree() if case["era"] == "legacy" else modern_tree()
    return mount_mcp(Bridge(tree))


def surface_for_sequence(sequence: dict[str, Any]):
    """Build ONE long-lived surface for a whole sequence.

    The opposite of :func:`surface_for` and the entire point of the
    section: the steps are replayed in order against a single handler, so
    state a request leaves behind is visible to the next one — which is
    how an adopter's persistent process actually serves traffic.
    """
    tree = legacy_tree() if sequence["era"] == "legacy" else modern_tree()
    return mount_mcp(Bridge(tree))


def request_for(case: dict[str, Any]) -> Request:
    """Turn a fixture case into a normalised request."""
    return Request(
        method="POST",
        path="/mcp",
        headers=Headers.from_mapping(case.get("headers")),
        body=case["request"].encode("utf-8"),
    )


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_wire_case_is_byte_exact(case: dict[str, Any]) -> None:
    """Each fixture case replays to byte-identical response and status."""
    response = surface_for(case).handle(request_for(case))

    assert response.status == case["status"], (
        f"{case['name']}: status {response.status} != {case['status']}"
    )
    expected = case["response"].encode("utf-8")
    assert response.body == expected, (
        f"{case['name']} body mismatch\n  expected: {expected!r}\n  actual:   {response.body!r}"
    )


@pytest.mark.parametrize("sequence", SEQUENCES, ids=[s["name"] for s in SEQUENCES])
def test_wire_sequence_is_byte_exact(sequence: dict[str, Any]) -> None:
    """Replay one sequence's steps, in order, against ONE handler.

    Sequences pin behaviour that only exists *between* requests. The one
    in the fixture today is cobra's lazily-attached ``--help`` flag: a
    leaf gains it on first execution, so two byte-identical
    ``tools/list`` requests either side of a ``tools/call`` legitimately
    return different bytes. Per-case isolation cannot see that, and it is
    the normal condition in an adopter's long-lived process.

    Each step asserts on the *cumulative* state, so a step that passes
    only because an earlier one failed to mutate anything still fails
    here — the step index is reported to make that obvious.
    """
    surface = surface_for_sequence(sequence)

    for index, step in enumerate(sequence["steps"]):
        response = surface.handle(request_for(step))
        label = f"{sequence['name']} step {index} ({step['name']})"

        assert response.status == step["status"], (
            f"{label}: status {response.status} != {step['status']}"
        )
        expected = step["response"].encode("utf-8")
        assert response.body == expected, (
            f"{label} body mismatch\n  expected: {expected!r}\n  actual:   {response.body!r}"
        )


def test_sequences_actually_depend_on_order() -> None:
    """A sequence must contain at least one order-dependent step.

    Without this, a sequence whose steps all happened to be independent
    would pass while proving nothing, and the section would quietly
    decay into a slower copy of ``cases``. The guard looks for two steps
    with identical request bytes and differing responses — the shape
    that per-case isolation structurally cannot express.

    Ids are stripped before grouping: they are per-step counters carrying
    no protocol meaning, and leaving them in would make every step
    trivially unique and this guard vacuous.
    """
    assert SEQUENCES, "fixture declares no sequences"

    for sequence in SEQUENCES:
        by_request: dict[str, set[str]] = {}
        for step in sequence["steps"]:
            key = _id_stripped(step["request"])
            by_request.setdefault(key, set()).add(_id_stripped(step["response"]))
        assert any(len(responses) > 1 for responses in by_request.values()), (
            f"{sequence['name']}: no step pair shares a request but differs in "
            "response, so nothing here needs a long-lived mount"
        )


def test_fixture_covers_both_eras() -> None:
    """Guard against a fixture edit that silently drops one era's coverage."""
    eras = {case["era"] for case in CASES}
    assert eras == {"legacy", "modern"}
    assert len(CASES) >= 17


def test_identical_requests_expect_identical_responses() -> None:
    """No entry under ``cases`` may depend on another having run first.

    ``cases`` were once generated from one long-lived server per era,
    which let a lazily-registered flag from an earlier invocation leak
    into a later ``tools/list`` — two byte-identical requests expecting
    different responses purely by position. That is fixed upstream, and
    this guard keeps it fixed: it groups cases by (era, routing headers,
    body) and asserts each group agrees on one answer.

    **Scoped to ``CASES`` on purpose — never widen it to ``SEQUENCES``.**
    Cross-request state is a bug in a case and the whole point of a
    sequence, so the same grouping applied there would fail on exactly
    the property the section exists to pin. The two sections encode
    opposite contracts and each needs its own guard;
    :func:`test_sequences_actually_depend_on_order` is the sequence half.
    """
    from collections import defaultdict

    grouped: dict[tuple, set] = defaultdict(set)
    for case in CASES:
        key = (
            case["era"],
            tuple(sorted(_routing_headers(case.get("headers")).items())),
            _id_stripped(case["request"]),
        )
        grouped[key].add((case["status"], _id_stripped(case["response"])))

    for key, answers in grouped.items():
        assert len(answers) == 1, f"position-dependent fixture case: {key}"


#: Headers the era detector does not read. ``MCP-Protocol-Version`` is the
#: documented non-marker: it predates the modern revision and is ignored on
#: the legacy path, so two cases differing only by it must produce the same
#: answer. Grouping on the full header set would let that pair drift apart
#: unnoticed, which is precisely how the original artefact hid.
NON_ROUTING_HEADERS = frozenset({"mcp-protocol-version"})


def _routing_headers(headers: dict[str, str] | None) -> dict[str, str]:
    """Drop headers that cannot change which handler serves a request."""
    return {
        name: value
        for name, value in (headers or {}).items()
        if name.lower() not in NON_ROUTING_HEADERS
    }


def _id_stripped(payload: str) -> str:
    """Blank out the JSON-RPC id so otherwise-identical cases compare equal.

    Ids are per-case counters carrying no protocol meaning; leaving them
    in would make every case trivially unique and the guard vacuous.
    """
    import re

    return re.sub(r'"id":\s*(?:"[^"]*"|[-\w.]+)', '"id":X', payload)


# --- the MRTR confirmation loop -------------------------------------------

#: The third fixture section, and the only one that is not byte-exact end
#: to end. Round 1 mints a fresh, time-bound ``requestState`` whose MAC
#: differs on every run, so only its *shape* is assertable; round 2 echoes
#: that state back and IS byte-exact.
MRTR: dict[str, Any] | None = FIXTURE_DOC.get("mrtr")


def mrtr_tree(counter: list[int]) -> Command:
    """The tree the ``mrtr`` fixture was captured against.

    Not one of the two era trees: neither carries a ``purge`` leaf, and
    the fixture's ``command_tree`` does not describe this one because the
    Go generator drives MRTR from a separate lock tree. ``purge`` is
    ``kit/requires-confirmation`` and echoes its ``target`` back, so the
    round-2 body pins *which* arguments survived the round trip rather
    than merely that something ran.

    ``counter`` is appended to on every execution.
    :meth:`Bridge.invoke` applies the enablement check and the
    destructive ceiling *before* delegating to the runner, so a gated
    leaf never reaches this callable and is never counted.
    """

    def purge(flags: Any) -> Result:
        counter.append(1)
        target = flags.get("target", "")
        return Result(stdout=f"purged {target if isinstance(target, str) else ''}\n")

    return Command(
        name="root",
        children=[
            Command(
                name="purge",
                short="Purge a target",
                run=purge,
                annotations={"kit/requires-confirmation": "true"},
                flags=[Flag("target", "what to purge", "string")],
            ),
        ],
    )


def _dig(root: Any, path: str) -> Any:
    """Read a dotted path out of a decoded result, for the fixture's assertions."""
    cur: Any = root
    for segment in path.split("."):
        if not isinstance(cur, dict):
            return None
        cur = cur.get(segment)
    return cur


def test_fixture_declares_an_mrtr_section() -> None:
    """A dropped ``mrtr`` section must fail loudly, not silently skip."""
    assert MRTR is not None, "fixture declares no mrtr section"


@pytest.mark.skipif(MRTR is None, reason="fixture declares no mrtr section")
def test_mrtr_round_trip() -> None:
    """Replay the confirmation loop against ONE mount keyed by the fixture.

    Round 1 must come back ``input_required`` with an elicitation prompt
    and *without* the leaf having run — that non-execution is the entire
    defect this section exists to catch, and only an execution count can
    prove it. A port gating on ``X-Confirm-Token`` alone would have
    refused at 428; a port with no gate at all would have executed.

    Round 2 substitutes the state *this port minted* into the fixture's
    template and is compared byte-exact. That pairing is what makes the
    exchange verifiable rather than merely plausible: a port that
    fabricated a plausible-looking round 1 could not produce a state its
    own round 2 accepts *and* land on Go's exact bytes.

    Both rounds share one mount keyed with the fixture's
    ``confirmation_key``. The state is a MAC over that key, so a mount
    with different key material cannot replay round 2.
    """
    assert MRTR is not None
    executions: list[int] = []
    surface = mount_mcp(
        Bridge(mrtr_tree(executions)),
        confirmation_key=MRTR["confirmation_key"].encode("utf-8"),
    )

    # --- Round 1: the prompt ---------------------------------------------
    first = surface.handle(
        Request(
            method="POST",
            path="/mcp",
            headers=Headers.from_mapping(MRTR["round1_headers"]),
            body=MRTR["round1_request"].encode("utf-8"),
        )
    )
    assert first.status == MRTR["round1_status"], (
        f"round1 status {first.status} != {MRTR['round1_status']}"
    )

    result = json.loads(first.body).get("result")
    assert isinstance(result, dict), "round1 carries no result object"

    assert not executions, "leaf executed before confirmation"

    for path, want in MRTR["round1_must_have"].items():
        assert _dig(result, path) == want, f"round1 {path}: {_dig(result, path)!r} != {want!r}"
    for absent in MRTR["round1_must_not_have"]:
        assert absent not in result, f"round1 must not carry {absent}"

    # Exactly one entry, under the reserved "confirm" key.
    assert list(result["inputRequests"]) == ["confirm"]

    # ``v1.<expiry-base10>.<mac>`` — three dot-separated parts. The MAC is
    # production-derived and never compared, only required to be present.
    state = result["requestState"]
    assert isinstance(state, str), "requestState is not a string"
    parts = state.split(".")
    assert len(parts) == 3, f"requestState framing: {state!r}"
    assert parts[0] == "v1", f"requestState version: {parts[0]!r}"
    assert parts[1].isdigit(), f"requestState expiry is not base-10: {parts[1]!r}"
    assert parts[2], "requestState mac is empty"

    # --- Round 2: the accepted retry, byte-exact --------------------------
    second = surface.handle(
        Request(
            method="POST",
            path="/mcp",
            headers=Headers.from_mapping(MRTR["round2_headers"]),
            body=MRTR["round2_request_template"].replace("{{requestState}}", state).encode("utf-8"),
        )
    )
    assert second.status == MRTR["round2_status"], (
        f"round2 status {second.status} != {MRTR['round2_status']}"
    )
    expected = MRTR["round2_response"].encode("utf-8")
    assert second.body == expected, (
        f"round2 body mismatch\n  expected: {expected!r}\n  actual:   {second.body!r}"
    )
    assert len(executions) == 1, f"executions after accept: {len(executions)}"
