"""Byte-exact conformance against the shared cross-language wire fixtures.

``sdk/tests/cross-lang/fixtures/mcp-wire.json`` is the parity contract for
all four MCP ports. It was generated by driving the Go surface over real
HTTP and capturing response bytes, so it is byte-identical to Go by
construction rather than by transcription.

"Byte-exact" is meant literally: each case's response is compared as
bytes, with no JSON decode/re-encode step on either side. Go sorts object
keys lexicographically, emits struct fields in declaration order, escapes
``<``/``>``/``&``, and appends a trailing newline; a port whose serialiser
differs has to reorder to match, not normalise the comparison away.

The fixture file also carries the command trees the cases were captured
against. Both are rebuilt here, because two cases differ only by which
tree served them.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from hop_top_kit.mcp import (
    Bridge,
    Command,
    Flag,
    Headers,
    Request,
    Result,
    mount_mcp,
)

FIXTURE = (
    Path(__file__).resolve().parents[2]
    / "tests"
    / "cross-lang"
    / "fixtures"
    / "mcp-wire.json"
)


def load_cases() -> list[dict[str, Any]]:
    """Read the fixture cases.

    A missing fixture is a hard failure, not a skip: this suite exists to
    prove parity, and a silently-skipped parity suite is worse than no
    suite at all.
    """
    if not FIXTURE.exists():  # pragma: no cover - fixture ships with the repo
        raise FileNotFoundError(f"wire fixture not found at {FIXTURE}")
    return json.loads(FIXTURE.read_text())["cases"]


# --- the two command trees the fixtures were captured against -------------


def legacy_tree() -> Command:
    """The tree behind every ``legacy/*`` case.

    ``widget add`` carries the full flag set including a hidden and a
    deprecated flag, both of which must be absent from the emitted
    schema.
    """
    return Command(
        name="root",
        children=[
            Command(
                name="widget",
                children=[
                    Command(
                        name="add",
                        short="Add a widget",
                        run=lambda flags: Result(stdout="added\n"),
                        annotations={"kit/side-effect": "write"},
                        flags=[
                            Flag("name", "widget name", "string", required=True),
                            Flag("count", "widget count", "int"),
                            Flag("force", "force flag", "bool"),
                            Flag("tag", "tag list", "stringSlice"),
                            Flag("hidden-flag", "should be hidden", "string", hidden=True),
                            Flag(
                                "deprecated-flag",
                                "should be dropped",
                                "string",
                                deprecated=True,
                            ),
                        ],
                    ),
                    Command(
                        name="delete",
                        short="Delete a widget",
                        run=lambda flags: Result(stdout="deleted\n"),
                        annotations={"kit/side-effect": "destructive"},
                    ),
                ],
            ),
            Command(
                name="secret",
                short="Locked",
                run=lambda flags: Result(),
                annotations={"kit/auth-required": "true"},
            ),
            Command(
                name="deploy",
                short="Deploy",
                run=lambda flags: Result(),
                annotations={"kit/requires-confirmation": "true"},
            ),
            Command(
                name="ping",
                short="Ping the server",
                run=lambda flags: Result(stdout="pong\n"),
                annotations={"kit/side-effect": "read"},
            ),
        ],
    )


def modern_tree() -> Command:
    """The tree behind every ``modern/*`` case.

    Deliberately not the legacy tree: ``widget add`` here declares only
    ``name`` and ``count``, and the fixture's modern ``tools/list``
    response pins exactly that narrower schema.
    """
    return Command(
        name="root",
        children=[
            Command(
                name="ping",
                short="Ping the server",
                run=lambda flags: Result(stdout="pong\n"),
                annotations={"kit/side-effect": "read"},
            ),
            Command(
                name="widget",
                children=[
                    Command(
                        name="add",
                        short="Add a widget",
                        run=lambda flags: Result(stdout="added\n"),
                        annotations={"kit/side-effect": "write"},
                        flags=[
                            Flag("name", "widget name", "string", required=True),
                            Flag("count", "widget count", "int"),
                        ],
                    ),
                    Command(
                        name="delete",
                        short="Delete a widget",
                        run=lambda flags: Result(stdout="deleted\n"),
                        annotations={"kit/side-effect": "destructive"},
                    ),
                ],
            ),
            Command(
                name="secret",
                short="Locked",
                run=lambda flags: Result(),
                annotations={"kit/auth-required": "true"},
            ),
            Command(
                name="deploy",
                short="Deploy",
                run=lambda flags: Result(),
                annotations={"kit/requires-confirmation": "true"},
            ),
        ],
    )


def surface_for(case: dict[str, Any]):
    """Build a fresh surface for one case.

    Fresh per case, deliberately. The fixtures are position-independent:
    each case is a self-contained request/response pair, and no case
    depends on another having run first. Sharing one surface across the
    suite would let per-case state leak forward and turn a passing run
    into an artefact of iteration order.
    """
    tree = legacy_tree() if case["era"] == "legacy" else modern_tree()
    return mount_mcp(Bridge(tree))


def request_for(case: dict[str, Any]) -> Request:
    """Turn a fixture case into a normalised request."""
    return Request(
        method="POST",
        path="/mcp",
        headers=Headers.from_mapping(case.get("headers")),
        body=case["request"].encode("utf-8"),
    )


CASES = load_cases()


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_wire_case_is_byte_exact(case: dict[str, Any]) -> None:
    """Each fixture case replays to byte-identical response and status."""
    response = surface_for(case).handle(request_for(case))

    assert response.status == case["status"], (
        f"{case['name']}: status {response.status} != {case['status']}"
    )
    expected = case["response"].encode("utf-8")
    assert response.body == expected, (
        f"{case['name']} body mismatch\n"
        f"  expected: {expected!r}\n"
        f"  actual:   {response.body!r}"
    )


def test_fixture_covers_both_eras() -> None:
    """Guard against a fixture edit that silently drops one era's coverage."""
    eras = {case["era"] for case in CASES}
    assert eras == {"legacy", "modern"}
    assert len(CASES) >= 17


def test_identical_requests_expect_identical_responses() -> None:
    """No case may depend on another having run first.

    The fixtures were once generated from one long-lived server per era,
    which let a lazily-registered flag from an earlier invocation leak
    into a later ``tools/list`` — two byte-identical requests expecting
    different responses purely by position. That is fixed upstream, and
    this guard keeps it fixed: it groups cases by (era, headers, body)
    and asserts each group agrees on one answer, so the artefact cannot
    silently return.
    """
    from collections import defaultdict

    grouped: dict[tuple, set] = defaultdict(set)
    for case in CASES:
        key = (
            case["era"],
            tuple(sorted(_routing_headers(case.get("headers")).items())),
            _id_stripped(case["request"]),
        )
        grouped[key].add((case["status"], _id_stripped(case["response"])))

    for key, answers in grouped.items():
        assert len(answers) == 1, f"position-dependent fixture case: {key}"


#: Headers the era detector does not read. ``MCP-Protocol-Version`` is the
#: documented non-marker: it predates the modern revision and is ignored on
#: the legacy path, so two cases differing only by it must produce the same
#: answer. Grouping on the full header set would let that pair drift apart
#: unnoticed, which is precisely how the original artefact hid.
NON_ROUTING_HEADERS = frozenset({"mcp-protocol-version"})


def _routing_headers(headers: dict[str, str] | None) -> dict[str, str]:
    """Drop headers that cannot change which handler serves a request."""
    return {
        name: value
        for name, value in (headers or {}).items()
        if name.lower() not in NON_ROUTING_HEADERS
    }


def _id_stripped(payload: str) -> str:
    """Blank out the JSON-RPC id so otherwise-identical cases compare equal.

    Ids are per-case counters carrying no protocol meaning; leaving them
    in would make every case trivially unique and the guard vacuous.
    """
    import re

    return re.sub(r'"id":\s*(?:"[^"]*"|[-\w.]+)', '"id":X', payload)
