// Command kit-bus-emit POSTs a PR-lifecycle kit bus event payload to
// the configured ingress endpoint. Invoked from the
// `.github/workflows/kit-bus-*.yml` files generated by kit init
// (T-0776).
//
// Inputs are passed via environment variables (the workflows set them
// from `${{ github.event.* }}` expressions) and one --kind flag that
// selects which of the four canonical topics to emit.
//
// Contract anchors:
//   - docs/contracts/kit-init-pr-wiring.md §2 (payload shape)
//   - docs/contracts/kit-init-pr-wiring.md §3 (gating + auth +
//     fail-open default, fail-closed under KIT_BUS_STRICT="true")
//   - go/runtime/bus/topics.go (ValidateTopic enforces 4-segment
//     past-tense lowercase form)
//
// Auth precedence: KIT_BUS_SIGNING_KEY (HMAC-SHA256 in
// `X-Kit-Bus-Signature`) wins over KIT_BUS_TOKEN (bearer in
// `Authorization`). If only one is set, it is used. If neither, the
// request is sent unauthenticated (ingress may reject; that surfaces
// as a non-2xx and follows the fail-open/closed rules).
//
// Bounded payload: failure_summary and excerpt are truncated to 256
// bytes with an ellipsis. We never include full log bodies or full
// comment bodies — listeners that need them fetch via the embedded
// URLs.
package main
