// Command vendor-gitleaks fetches the upstream gitleaks default config at a
// pinned tag and splits it into two files for kit/scope:
//
//   - gitleaks-paths.toml    — global [allowlist] block (paths + extends);
//     consumed by scope.SecretPaths() at init.
//   - gitleaks-content.toml  — full config (rules + allowlists); staged for
//     future kit/redact. Preserves nested
//     [[rules.allowlists]] structure verbatim.
//
// Also emits SOURCES.md (provenance), LICENSE (Apache-2.0 verbatim), and
// NOTICE (attribution).
//
// Usage:
//
//	go run ./tools/vendor-gitleaks --tag v8.30.1 --out go/core/scope/rules/
//
// Idempotent: same --tag → byte-identical output. Resolves the tag to its
// commit SHA via the GitHub API and pins downloads to that SHA.
package main

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
)

const (
	owner       = "gitleaks"
	repo        = "gitleaks"
	upstreamRel = "config/gitleaks.toml"
	licenseRel  = "LICENSE"
)

func main() {
	var (
		tag    = flag.String("tag", "", "upstream gitleaks release tag (e.g. v8.30.1)")
		outDir = flag.String("out", "", "output directory (e.g. go/core/scope/rules/)")
	)
	flag.Parse()

	if *tag == "" || *outDir == "" {
		fmt.Fprintln(os.Stderr, "usage: vendor-gitleaks --tag <tag> --out <dir>")
		os.Exit(2)
	}

	sha, err := resolveSHA(*tag)
	if err != nil {
		die("resolve tag %s: %v", *tag, err)
	}

	rawTOML, err := fetch(rawURL(sha, upstreamRel))
	if err != nil {
		die("fetch %s: %v", upstreamRel, err)
	}
	rawLicense, err := fetch(rawURL(sha, licenseRel))
	if err != nil {
		die("fetch %s: %v", licenseRel, err)
	}

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		die("mkdir %s: %v", *outDir, err)
	}

	if err := writePaths(filepath.Join(*outDir, "gitleaks-paths.toml"), rawTOML, *tag, sha); err != nil {
		die("write paths: %v", err)
	}
	if err := writeContent(filepath.Join(*outDir, "gitleaks-content.toml"), rawTOML, *tag, sha); err != nil {
		die("write content: %v", err)
	}
	if err := writeFile(filepath.Join(*outDir, "LICENSE"), rawLicense); err != nil {
		die("write LICENSE: %v", err)
	}
	if err := writeNotice(filepath.Join(*outDir, "NOTICE"), *tag); err != nil {
		die("write NOTICE: %v", err)
	}
	if err := writeSources(filepath.Join(*outDir, "SOURCES.md"), *tag, sha); err != nil {
		die("write SOURCES.md: %v", err)
	}

	fmt.Printf("vendored gitleaks %s (%s) → %s\n", *tag, sha[:12], *outDir)
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "vendor-gitleaks: "+format+"\n", args...)
	os.Exit(1)
}

func rawURL(sha, path string) string {
	return fmt.Sprintf("https://raw.githubusercontent.com/%s/%s/%s/%s", owner, repo, sha, path)
}

// resolveSHA resolves an annotated/lightweight tag to its commit SHA using
// the gh CLI (auth + paginated; no extra deps). Falls back to git ls-remote
// if gh is unavailable.
func resolveSHA(tag string) (string, error) {
	if out, err := exec.Command("gh", "api",
		fmt.Sprintf("repos/%s/%s/commits/%s", owner, repo, tag),
		"--jq", ".sha").Output(); err == nil {
		sha := strings.TrimSpace(string(out))
		if len(sha) == 40 {
			return sha, nil
		}
	}
	out, err := exec.Command("git", "ls-remote",
		fmt.Sprintf("https://github.com/%s/%s.git", owner, repo),
		"refs/tags/"+tag).Output()
	if err != nil {
		return "", err
	}
	parts := strings.Fields(string(out))
	if len(parts) == 0 {
		return "", fmt.Errorf("tag %s not found", tag)
	}
	return parts[0], nil
}

func fetch(url string) ([]byte, error) {
	c := &http.Client{Timeout: 30 * time.Second}
	resp, err := c.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("status %d: %s", resp.StatusCode, url)
	}
	return io.ReadAll(resp.Body)
}

// pathsConfig mirrors the gitleaks global [allowlist] block (we only need
// paths + extends for scope's path-skipping logic).
type pathsConfig struct {
	Allowlist struct {
		Description string   `toml:"description"`
		Paths       []string `toml:"paths"`
	} `toml:"allowlist"`
	Extend struct {
		UseDefault bool   `toml:"useDefault"`
		Path       string `toml:"path"`
	} `toml:"extend"`
}

func writePaths(out string, raw []byte, tag, sha string) error {
	var cfg pathsConfig
	if _, err := toml.Decode(string(raw), &cfg); err != nil {
		return fmt.Errorf("decode upstream TOML: %w", err)
	}

	var b strings.Builder
	fmt.Fprintln(&b, "# AUTO-GENERATED by tools/vendor-gitleaks. DO NOT EDIT.")
	fmt.Fprintln(&b, "#")
	fmt.Fprintf(&b, "# Source:  github.com/%s/%s@%s (%s)\n", owner, repo, tag, sha)
	fmt.Fprintln(&b, "# License: Apache-2.0 (see LICENSE in this dir)")
	fmt.Fprintln(&b, "# Refresh: make refresh-secret-rules")
	fmt.Fprintln(&b, "#")
	fmt.Fprintln(&b, "# Subset of the gitleaks default config containing the global [allowlist]")
	fmt.Fprintln(&b, "# paths array. Consumed by scope.SecretPaths() to seed the default deny set.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "[allowlist]")
	if cfg.Allowlist.Description != "" {
		fmt.Fprintf(&b, "description = %s\n", quoteBasic(cfg.Allowlist.Description))
	}
	fmt.Fprintln(&b, "paths = [")
	for _, p := range cfg.Allowlist.Paths {
		fmt.Fprintf(&b, "    %s,\n", quoteLiteral(p))
	}
	fmt.Fprintln(&b, "]")

	return writeFile(out, []byte(b.String()))
}

func writeContent(out string, raw []byte, tag, sha string) error {
	// Preserve the upstream TOML verbatim (rules + nested allowlists are
	// hard to round-trip via marshalling without losing comments/order).
	// Just prepend a provenance header.
	var b strings.Builder
	fmt.Fprintln(&b, "# AUTO-GENERATED by tools/vendor-gitleaks. DO NOT EDIT.")
	fmt.Fprintln(&b, "#")
	fmt.Fprintf(&b, "# Source:  github.com/%s/%s@%s (%s)\n", owner, repo, tag, sha)
	fmt.Fprintln(&b, "# License: Apache-2.0 (see LICENSE in this dir)")
	fmt.Fprintln(&b, "# Refresh: make refresh-secret-rules")
	fmt.Fprintln(&b, "#")
	fmt.Fprintln(&b, "# Full upstream gitleaks config preserved verbatim. Staged for future")
	fmt.Fprintln(&b, "# kit/redact use; not parsed by scope.")
	fmt.Fprintln(&b)
	b.Write(raw)
	return writeFile(out, []byte(b.String()))
}

func writeNotice(out, tag string) error {
	body := fmt.Sprintf(`kit/scope vendored secret-detection rules

This directory contains files derived from the gitleaks project
(https://github.com/gitleaks/gitleaks), pinned to release %s.

Original work Copyright (c) 2019-2026 Zachary Rice and contributors.
Licensed under the Apache License, Version 2.0 (see LICENSE).

Modifications by the kit project: split into gitleaks-paths.toml
(global [allowlist] only, consumed by scope) and gitleaks-content.toml
(full config preserved). No rule semantics changed.
`, tag)
	return writeFile(out, []byte(body))
}

func writeSources(out, tag, sha string) error {
	body := fmt.Sprintf(`# Vendored Sources

| File                   | Source                                              | License    |
|------------------------|-----------------------------------------------------|------------|
| gitleaks-paths.toml    | github.com/gitleaks/gitleaks @ %s | Apache-2.0 |
| gitleaks-content.toml  | github.com/gitleaks/gitleaks @ %s | Apache-2.0 |
| LICENSE                | github.com/gitleaks/gitleaks @ %s | Apache-2.0 |

## Pinned Commit

- Tag:    %s
- SHA:    %s
- URL:    https://github.com/gitleaks/gitleaks/tree/%s/config/gitleaks.toml

## Refresh

`+"```"+`
make refresh-secret-rules
`+"```"+`

The Makefile target re-runs `+"`tools/vendor-gitleaks`"+` against the latest
tagged release. Same tag → byte-identical output.
`,
		tag, tag, tag, tag, sha, sha)
	return writeFile(out, []byte(body))
}

func writeFile(path string, data []byte) error {
	return os.WriteFile(path, data, 0o644)
}

// quoteLiteral wraps s in TOML literal-string triple-quotes (”') so regex
// backslashes survive verbatim. Falls back to single-quote literal if no
// triple-quote required.
func quoteLiteral(s string) string {
	if strings.Contains(s, "'''") {
		// Pathological case (no upstream paths use ''' — fall back to basic).
		return quoteBasic(s)
	}
	return "'''" + s + "'''"
}

// quoteBasic wraps s in a TOML basic string with escapes.
func quoteBasic(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
