// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: crud.proto

package crudv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hop.top/kit/contracts/proto/crud/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EntityServiceName is the fully-qualified name of the EntityService service.
	EntityServiceName = "crud.v1.EntityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EntityServiceCreateProcedure is the fully-qualified name of the EntityService's Create RPC.
	EntityServiceCreateProcedure = "/crud.v1.EntityService/Create"
	// EntityServiceGetProcedure is the fully-qualified name of the EntityService's Get RPC.
	EntityServiceGetProcedure = "/crud.v1.EntityService/Get"
	// EntityServiceListProcedure is the fully-qualified name of the EntityService's List RPC.
	EntityServiceListProcedure = "/crud.v1.EntityService/List"
	// EntityServiceUpdateProcedure is the fully-qualified name of the EntityService's Update RPC.
	EntityServiceUpdateProcedure = "/crud.v1.EntityService/Update"
	// EntityServiceDeleteProcedure is the fully-qualified name of the EntityService's Delete RPC.
	EntityServiceDeleteProcedure = "/crud.v1.EntityService/Delete"
)

// EntityServiceClient is a client for the crud.v1.EntityService service.
type EntityServiceClient interface {
	// Create persists a new entity and returns the stored result.
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	// Get retrieves a single entity by ID.
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
	// List returns entities matching the query parameters.
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	// Update replaces an existing entity and returns the result.
	Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error)
	// Delete removes an entity by ID.
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
}

// NewEntityServiceClient constructs a client for the crud.v1.EntityService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEntityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EntityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	entityServiceMethods := v1.File_crud_proto.Services().ByName("EntityService").Methods()
	return &entityServiceClient{
		create: connect.NewClient[v1.CreateRequest, v1.CreateResponse](
			httpClient,
			baseURL+EntityServiceCreateProcedure,
			connect.WithSchema(entityServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.GetRequest, v1.GetResponse](
			httpClient,
			baseURL+EntityServiceGetProcedure,
			connect.WithSchema(entityServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+EntityServiceListProcedure,
			connect.WithSchema(entityServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.UpdateRequest, v1.UpdateResponse](
			httpClient,
			baseURL+EntityServiceUpdateProcedure,
			connect.WithSchema(entityServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.DeleteRequest, v1.DeleteResponse](
			httpClient,
			baseURL+EntityServiceDeleteProcedure,
			connect.WithSchema(entityServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// entityServiceClient implements EntityServiceClient.
type entityServiceClient struct {
	create *connect.Client[v1.CreateRequest, v1.CreateResponse]
	get    *connect.Client[v1.GetRequest, v1.GetResponse]
	list   *connect.Client[v1.ListRequest, v1.ListResponse]
	update *connect.Client[v1.UpdateRequest, v1.UpdateResponse]
	delete *connect.Client[v1.DeleteRequest, v1.DeleteResponse]
}

// Create calls crud.v1.EntityService.Create.
func (c *entityServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Get calls crud.v1.EntityService.Get.
func (c *entityServiceClient) Get(ctx context.Context, req *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// List calls crud.v1.EntityService.List.
func (c *entityServiceClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Update calls crud.v1.EntityService.Update.
func (c *entityServiceClient) Update(ctx context.Context, req *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls crud.v1.EntityService.Delete.
func (c *entityServiceClient) Delete(ctx context.Context, req *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// EntityServiceHandler is an implementation of the crud.v1.EntityService service.
type EntityServiceHandler interface {
	// Create persists a new entity and returns the stored result.
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	// Get retrieves a single entity by ID.
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
	// List returns entities matching the query parameters.
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	// Update replaces an existing entity and returns the result.
	Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error)
	// Delete removes an entity by ID.
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
}

// NewEntityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEntityServiceHandler(svc EntityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	entityServiceMethods := v1.File_crud_proto.Services().ByName("EntityService").Methods()
	entityServiceCreateHandler := connect.NewUnaryHandler(
		EntityServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(entityServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	entityServiceGetHandler := connect.NewUnaryHandler(
		EntityServiceGetProcedure,
		svc.Get,
		connect.WithSchema(entityServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	entityServiceListHandler := connect.NewUnaryHandler(
		EntityServiceListProcedure,
		svc.List,
		connect.WithSchema(entityServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	entityServiceUpdateHandler := connect.NewUnaryHandler(
		EntityServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(entityServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	entityServiceDeleteHandler := connect.NewUnaryHandler(
		EntityServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(entityServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/crud.v1.EntityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EntityServiceCreateProcedure:
			entityServiceCreateHandler.ServeHTTP(w, r)
		case EntityServiceGetProcedure:
			entityServiceGetHandler.ServeHTTP(w, r)
		case EntityServiceListProcedure:
			entityServiceListHandler.ServeHTTP(w, r)
		case EntityServiceUpdateProcedure:
			entityServiceUpdateHandler.ServeHTTP(w, r)
		case EntityServiceDeleteProcedure:
			entityServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEntityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEntityServiceHandler struct{}

func (UnimplementedEntityServiceHandler) Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crud.v1.EntityService.Create is not implemented"))
}

func (UnimplementedEntityServiceHandler) Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crud.v1.EntityService.Get is not implemented"))
}

func (UnimplementedEntityServiceHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crud.v1.EntityService.List is not implemented"))
}

func (UnimplementedEntityServiceHandler) Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crud.v1.EntityService.Update is not implemented"))
}

func (UnimplementedEntityServiceHandler) Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crud.v1.EntityService.Delete is not implemented"))
}
