// Package rules embeds the vendored gitleaks rule corpora as byte slices
// so kit/scope and kit/redact can share the byte-identical files without
// duplicating them on disk.
//
// The TOML files in this directory are AUTO-GENERATED by
// tools/vendor-gitleaks. Do not edit by hand. Refresh via
// `make refresh-secret-rules`.
package rules

import _ "embed"

// GitleaksContent is the full gitleaks rule TOML (rules + nested
// allowlists). Consumed by kit/redact's loader.
//
//go:embed gitleaks-content.toml
var GitleaksContent []byte

// GitleaksPaths is the path-allowlist subset (global [allowlist] paths
// only). Consumed by kit/scope's SecretPaths().
//
//go:embed gitleaks-paths.toml
var GitleaksPaths []byte
