package api_test

import (
	"encoding/json"
	"errors"
	"flag"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"hop.top/kit/go/transport/api"
)

var updateAuthWire = flag.Bool("update-auth-wire", false,
	"rewrite testdata/protected-resource-wire.json from the live guard")

// AuthWireCase is one exchange of the protected-resource wire fixture:
// a request to an endpoint behind [api.ProtectedResource.Guard], and
// the status, headers and body the guard answers.
type AuthWireCase struct {
	Name    string            `json:"name"`
	Why     string            `json:"why"`
	Method  string            `json:"method"`
	Path    string            `json:"path"`
	Auth    string            `json:"authorization,omitempty"`
	Status  int               `json:"status"`
	Headers map[string]string `json:"headers,omitempty"`
	Body    string            `json:"body,omitempty"`
}

// AuthWireFixture is the fixture: the resource the guard describes and
// the exchanges. Every kit MCP mount behind the authorization flow
// answers them byte for byte (mcpsdk.WithProtectedResource,
// cmdsurface.WithMCPProtectedResource, the mcp service).
type AuthWireFixture struct {
	Comment              string         `json:"_comment"`
	Resource             string         `json:"resource"`
	AuthorizationServers []string       `json:"authorization_servers"`
	GoodToken            string         `json:"good_token"`
	Cases                []AuthWireCase `json:"cases"`
}

// authWireHeaders are the response headers the fixture pins.
var authWireHeaders = []string{"Content-Type", "WWW-Authenticate", "Access-Control-Allow-Origin", "Allow"}

// AuthWireFixturePath is where the fixture lives, for the mounts'
// tests in other packages.
const authWireFixture = "testdata/protected-resource-wire.json"

func authWireSeed() AuthWireFixture {
	return AuthWireFixture{
		Comment: "Generated by go test ./go/transport/api -run TestProtectedResourceWire -update-auth-wire. " +
			"The MCP authorization flow (RFC 9728) at the HTTP edge of every kit MCP mount.",
		Resource:             "https://mcp.example.com/mcp",
		AuthorizationServers: []string{"https://login.example.com"},
		GoodToken:            "good",
		Cases: []AuthWireCase{
			{Name: "metadata", Why: "the document answers without a token", Method: "GET",
				Path: "/.well-known/oauth-protected-resource/mcp"},
			{Name: "metadata-preflight", Why: "a browser client may fetch it cross-origin", Method: "OPTIONS",
				Path: "/.well-known/oauth-protected-resource/mcp"},
			{Name: "metadata-post", Why: "the document is read-only", Method: "POST",
				Path: "/.well-known/oauth-protected-resource/mcp"},
			{Name: "no-token", Why: "401 names the document in resource_metadata", Method: "POST", Path: "/mcp"},
			{Name: "bad-token", Why: "a refused token is answered the same way", Method: "POST", Path: "/mcp",
				Auth: "Bearer bad"},
		},
	}
}

// ServeAuthWire answers c against h and fills the status, pinned
// headers and body.
func serveAuthWire(h http.Handler, c AuthWireCase) AuthWireCase {
	rec := httptest.NewRecorder()
	req := httptest.NewRequest(c.Method, c.Path, strings.NewReader(`{"jsonrpc":"2.0","id":1,"method":"ping"}`))
	if c.Auth != "" {
		req.Header.Set("Authorization", c.Auth)
	}
	h.ServeHTTP(rec, req)
	c.Status = rec.Code
	c.Headers = map[string]string{}
	for _, k := range authWireHeaders {
		if v := rec.Header().Get(k); v != "" {
			c.Headers[k] = v
		}
	}
	c.Body = rec.Body.String()
	return c
}

// TestProtectedResourceWire pins the guard's wire against the fixture.
func TestProtectedResourceWire(t *testing.T) {
	seed := authWireSeed()
	pr, err := api.NewProtectedResource(seed.Resource, seed.AuthorizationServers, nil)
	require.NoError(t, err)
	h := pr.Guard(func(r *http.Request) (any, error) {
		if r.Header.Get("Authorization") == "Bearer "+seed.GoodToken {
			return api.Claims{Subject: "alice"}, nil
		}
		return nil, errors.New("invalid token")
	})(http.NotFoundHandler())

	got := seed
	got.Cases = nil
	for _, c := range seed.Cases {
		got.Cases = append(got.Cases, serveAuthWire(h, c))
	}
	path := filepath.FromSlash(authWireFixture)
	if *updateAuthWire {
		data, err := json.MarshalIndent(got, "", "  ")
		require.NoError(t, err)
		require.NoError(t, os.WriteFile(path, append(data, '\n'), 0o644))
	}
	data, err := os.ReadFile(path)
	require.NoError(t, err, "run with -update-auth-wire to create it")
	var want AuthWireFixture
	require.NoError(t, json.Unmarshal(data, &want))
	require.Equal(t, want, got)
}
