#!/usr/bin/env bash
#
# kit init — .githooks/post-pr-open
#
# Generated by `kit init` per docs/contracts/kit-init-pr-wiring.md
# (sections 2, 3, 5, 6, 8). Edit at your own risk: a future `kit init`
# augment run will detect divergence from the kit-generated content and
# write your edits to <path>.kit-suggested instead of overwriting them.
#
# When to run: after `gh pr create` (or any equivalent PR-open path)
# succeeds. Invoke directly or wire into a wrapper command — the hook is
# safe to run multiple times against the same PR; duplicate-prevention
# keys on (repo, PR number, event family) and skips when an open
# follow-up already exists.
#
# What it does:
#   1. Reads PR metadata from `gh pr view` against HEAD.
#   2. Probes ${KIT_BUS_INGRESS_URL%/}/healthz with a 5-second timeout.
#   3. Push path: when the probe returns HTTP 2xx within 5s AND
#      KIT_BUS_ENABLED == "true", trusts a remote bus host to deliver
#      follow-ups. Logs one stderr note and exits 0 — no local task.
#   4. Pull path: otherwise (bus disabled, probe failed, non-2xx, DNS
#      error, TLS error, timeout), creates a scheduled `tlc` task due
#      10 minutes from now with kit:pr-followup + the full canonical
#      topic tag (e.g. event:github.pr.run.completed), the PR URL, head
#      SHA, branch, and a track/task link resolved from the branch name
#      when it matches t-NNNN-*.
#
# Fail-open: missing `tlc` or `gh` on PATH never blocks PR creation;
# the hook prints one actionable stderr line and exits 0.
#
# Configuration (environment, not flags — the hook is invoked by other
# tools and must compose cleanly):
#   KIT_BUS_ENABLED        "true" → enable push path probe
#   KIT_BUS_INGRESS_URL    base URL; "/healthz" is appended
#   KIT_POST_PR_HOOK_DEBUG "1" → trace decisions on stderr
#   KIT_POST_PR_HOOK_FAMILY override the event family tag (default: run)
#   KIT_POST_PR_HOOK_DUE   override the tlc --due value (default: in 10m)

set -u
# Do NOT `set -e`: each section is responsible for its own exit policy
# and the hook must never propagate a non-zero exit upstream — that
# would defeat fail-open.

KIT_POST_PR_HOOK_DEBUG="${KIT_POST_PR_HOOK_DEBUG:-0}"
KIT_POST_PR_HOOK_FAMILY="${KIT_POST_PR_HOOK_FAMILY:-run}"
KIT_POST_PR_HOOK_DUE="${KIT_POST_PR_HOOK_DUE:-in 10m}"

kit_log() {
  # One-line stderr note. Prefix keeps logs greppable.
  printf 'kit: %s\n' "$*" >&2
}

kit_debug() {
  [ "${KIT_POST_PR_HOOK_DEBUG}" = "1" ] || return 0
  printf 'kit-debug: %s\n' "$*" >&2
}

# Map the short event family (used only as a local label and inside the
# dedup-key tag) to the full 4-segment canonical topic name expected by
# bus.ValidateTopic. The per-event tag value carries the full topic so
# downstream filtering is not lossy. Unknown families fall back to
# "github.pr.${family}" — invalid for the bus, but kept distinguishable
# so adopters see exactly what their override produced.
kit_canonical_topic() {
  case "$1" in
    run)     printf 'github.pr.run.completed' ;;
    comment) printf 'github.pr.comment.created' ;;
    merged)  printf 'github.pr.pull.merged' ;;
    closed)  printf 'github.pr.pull.closed' ;;
    *)       printf 'github.pr.%s' "$1" ;;
  esac
}

# ----- 1. discover gh + read PR metadata --------------------------------------

if ! command -v gh >/dev/null 2>&1; then
  kit_log "gh not found on PATH; skipping scheduled follow-up"
  exit 0
fi

# `gh pr view` against HEAD picks the PR matching the current branch.
# --json keeps the fields stable across gh versions.
PR_JSON="$(gh pr view --json number,url,headRefName,headRefOid,title,body,baseRepository 2>/dev/null || true)"

if [ -z "${PR_JSON}" ]; then
  kit_log "no open PR for current branch; skipping scheduled follow-up"
  exit 0
fi

# Minimal JSON field extraction. gh emits compact JSON for these scalar
# fields; sed-based extraction keeps the hook portable without adding a
# jq dependency. The patterns assume gh's documented field shapes (no
# embedded newlines in `title`; URLs and SHAs are RFC-safe).
extract_field() {
  printf '%s' "$1" | sed -n "s/.*\"$2\":\"\\([^\"]*\\)\".*/\\1/p" | head -n1
}
extract_number() {
  printf '%s' "$1" | sed -n "s/.*\"$2\":\\([0-9][0-9]*\\).*/\\1/p" | head -n1
}

PR_NUMBER="$(extract_number "${PR_JSON}" number)"
PR_URL="$(extract_field "${PR_JSON}" url)"
PR_BRANCH="$(extract_field "${PR_JSON}" headRefName)"
PR_HEAD_SHA="$(extract_field "${PR_JSON}" headRefOid)"
PR_TITLE="$(extract_field "${PR_JSON}" title)"
# baseRepository.{owner.login, name} are nested; degrade to "" when gh
# omits them under older versions. The probe + tagging tolerates an
# empty repo string.
PR_REPO_OWNER="$(printf '%s' "${PR_JSON}" | sed -n 's/.*"baseRepository":{[^}]*"login":"\([^"]*\)".*/\1/p' | head -n1)"
PR_REPO_NAME="$(printf '%s' "${PR_JSON}" | sed -n 's/.*"baseRepository":{[^}]*"name":"\([^"]*\)".*/\1/p' | head -n1)"
PR_REPO=""
if [ -n "${PR_REPO_OWNER}" ] && [ -n "${PR_REPO_NAME}" ]; then
  PR_REPO="${PR_REPO_OWNER}/${PR_REPO_NAME}"
fi

if [ -z "${PR_NUMBER}" ]; then
  kit_log "could not parse PR number from gh output; skipping scheduled follow-up"
  exit 0
fi

kit_debug "PR #${PR_NUMBER} url=${PR_URL} branch=${PR_BRANCH} head=${PR_HEAD_SHA} repo=${PR_REPO}"

# ----- 2. resolve originating task from branch --------------------------------

# Mirror cmd/kit/init/posthook.go ResolveTaskIDFromBranch:
#   ^[tT]-(\d{3,6})(?:-|$) → "T-NNNN"
TASK_ID=""
case "${PR_BRANCH}" in
  [tT]-[0-9][0-9][0-9]|[tT]-[0-9][0-9][0-9]-*|\
  [tT]-[0-9][0-9][0-9][0-9]|[tT]-[0-9][0-9][0-9][0-9]-*|\
  [tT]-[0-9][0-9][0-9][0-9][0-9]|[tT]-[0-9][0-9][0-9][0-9][0-9]-*|\
  [tT]-[0-9][0-9][0-9][0-9][0-9][0-9]|[tT]-[0-9][0-9][0-9][0-9][0-9][0-9]-*)
    # Extract leading digits after the "x-" prefix.
    NUM="$(printf '%s' "${PR_BRANCH}" | sed -n 's/^[tT]-\([0-9][0-9]*\).*$/\1/p')"
    TASK_ID="T-${NUM}"
    ;;
esac
kit_debug "task-id from branch: ${TASK_ID:-<none>}"

# ----- 3. liveness probe (push path) ------------------------------------------

# Default to pull path; flip to push only when both gating conditions
# resolve true and the probe returns 2xx within 5s.
USE_PUSH=0

if [ "${KIT_BUS_ENABLED:-}" = "true" ] && [ -n "${KIT_BUS_INGRESS_URL:-}" ]; then
  # Strip a trailing slash to match the contract path: ${URL%/}/healthz.
  PROBE_URL="${KIT_BUS_INGRESS_URL%/}/healthz"
  kit_debug "probing ${PROBE_URL} (5s timeout)"

  if command -v curl >/dev/null 2>&1; then
    # --max-time bounds total time; --connect-timeout bounds the TCP
    # handshake. -o /dev/null silences body; -w prints just the status.
    STATUS_CODE="$(curl --silent --output /dev/null \
      --max-time 5 --connect-timeout 5 \
      --write-out '%{http_code}' \
      "${PROBE_URL}" 2>/dev/null || true)"
  else
    # No curl: degrade to pull. (We could try wget here too; keeping
    # the surface narrow keeps the hook auditable.)
    STATUS_CODE=""
    kit_debug "curl not on PATH; bus probe skipped, falling through to pull path"
  fi
  kit_debug "probe status=${STATUS_CODE}"

  case "${STATUS_CODE}" in
    2*)
      USE_PUSH=1
      ;;
  esac
fi

if [ "${USE_PUSH}" = "1" ]; then
  kit_log "bus ingress healthy, deferring follow-up to host listener"
  exit 0
fi

# ----- 4. pull path: schedule tlc follow-up -----------------------------------

if ! command -v tlc >/dev/null 2>&1; then
  kit_log "tlc not found on PATH; skipping scheduled follow-up for PR #${PR_NUMBER}"
  exit 0
fi

# Duplicate-prevention key: (repo, PR number, event family). Encoded as
# a per-triple tag so tlc's --tag filter resolves the lookup in one call.
# Strip slashes from repo so the tag value stays opaque to tlc's tag
# parser (kit:pr-followup:<owner>-<name>:<pr>:<family>).
REPO_TAG="$(printf '%s' "${PR_REPO}" | tr '/' '-')"
DEDUP_TAG="kit:pr-followup:${REPO_TAG}:${PR_NUMBER}:${KIT_POST_PR_HOOK_FAMILY}"

# tlc task list filters by tag; if any open (TODO/in_progress) task
# matches, we treat the follow-up as already scheduled and skip.
# A closed-then-reopened PR re-runs this hook; the prior follow-up is
# either DONE (PR was merged/closed) or stale (no match by status), so
# the dedup query sees zero open matches and creates a fresh task.
EXISTING="$(tlc task list \
  --tag "${DEDUP_TAG}" \
  --status TODO \
  --status in_progress \
  --format json 2>/dev/null || true)"

if [ -n "${EXISTING}" ] && [ "${EXISTING}" != "[]" ] && [ "${EXISTING}" != "null" ]; then
  # Heuristic: any non-empty array means an open follow-up exists.
  # We intentionally do not parse the JSON further — the dedup tag
  # itself encodes the triple, and tlc enforces status filtering.
  case "${EXISTING}" in
    *'"id"'*)
      kit_log "follow-up already scheduled for PR #${PR_NUMBER} (${KIT_POST_PR_HOOK_FAMILY}); skipping"
      exit 0
      ;;
  esac
fi

# Build the create command. tlc --due accepts natural-language ("in 10m")
# and absolute ("2026-05-23T14:10:00Z") forms; we pass-through whatever
# KIT_POST_PR_HOOK_DUE resolves to (default: "in 10m").
CANONICAL_TOPIC="$(kit_canonical_topic "${KIT_POST_PR_HOOK_FAMILY}")"
TASK_TITLE="Review PR #${PR_NUMBER}: ${PR_TITLE}"
TASK_DESCRIPTION="Auto-scheduled by kit post-pr-open hook.

PR:        ${PR_URL}
PR #:      ${PR_NUMBER}
Branch:    ${PR_BRANCH}
Head SHA:  ${PR_HEAD_SHA}
Repo:      ${PR_REPO}
Family:    ${KIT_POST_PR_HOOK_FAMILY}
Trigger:   ${CANONICAL_TOPIC}
Task link: ${TASK_ID}
"

# Compose tlc args. --tag is repeatable; we pass all three tags
# (the fixed kit:pr-followup, the per-event canonical tag carrying the
# full 4-segment topic, and the dedup-key tag whose family segment stays
# as the short label).
set -- task create "${TASK_TITLE}" \
  --description "${TASK_DESCRIPTION}" \
  --due "${KIT_POST_PR_HOOK_DUE}" \
  --tag "kit:pr-followup" \
  --tag "event:${CANONICAL_TOPIC}" \
  --tag "${DEDUP_TAG}"

if [ -n "${TASK_ID}" ]; then
  # tlc resolves --track against the configured track index; when the
  # branch-derived task ID points to a track rather than a task, this
  # link still resolves (tlc treats unknown IDs as opaque references).
  set -- "$@" --reference "${TASK_ID}"
fi

if ! tlc "$@" >/dev/null 2>&1; then
  # tlc failures must not block PR creation — log + exit 0.
  kit_log "tlc task create failed for PR #${PR_NUMBER}; check 'tlc doctor' or rerun manually"
  exit 0
fi

kit_log "scheduled tlc follow-up for PR #${PR_NUMBER} (${KIT_POST_PR_HOOK_FAMILY}, due ${KIT_POST_PR_HOOK_DUE})"
exit 0
