// Package kitinit — releaseplease.go renders the release-please caller:
// `.github/workflows/release-please.yml`, a stub that `uses:` the
// hop-top/.github `release-please-on-push.yml` reusable workflow (App
// token, per-branch concurrency guard, config check).
//
// The caller keeps the file name adopters already use for release-please
// (not `*-caller.yml`): the workflow's identity — run history,
// `gh workflow run release-please.yml`, the preflight's default path —
// survives a migration, and an existing hand-written file at that path
// falls under the ordinary never-overwrite policy.
//
// Contract: docs/contracts/kit-init-pr-wiring.md (Sections 1, 6, 8).
//
// Beyond the Section 6 conflict policy this generator also guarantees:
//   - never a second live release-please workflow: when any other
//     workflow already runs release-please, the caller is only offered
//     as a `.kit-suggested` sibling and the other file is reported;
//   - migration is opt-in (Inputs.MigrateReleasePlease) and replaces
//     only a plain workflow (releaseplease_classify.go) that is
//     committed and unmodified in git, so the replaced content stays
//     recoverable; custom workflows are reported, never rewritten;
//   - settings (triggers, config paths, target branch) are read back
//     from the live caller on every run, so a refresh never undoes
//     what a migration carried over;
//   - kit never writes release-please config or manifest (tag shape,
//     channels and labels are per-repo decisions): a missing pair is
//     reported, and the reusable workflow skips until it exists.
package kitinit

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

const (
	releasePleaseCallerRel = ".github/workflows/release-please.yml"
	releasePleaseReusable  = "release-please-on-push.yml"

	// The reusable workflow's input defaults (org layout).
	releasePleaseDefaultConfig   = ".github/release-please-config.json"
	releasePleaseDefaultManifest = ".github/.release-please-manifest.json"
)

// releasePleaseSettings is everything a caller varies. Empty strings
// mean "the reusable workflow's default".
type releasePleaseSettings struct {
	Branches     []string // push trigger; empty = no push trigger
	Dispatch     bool     // workflow_dispatch trigger
	ConfigFile   string
	ManifestFile string
	TargetBranch string
}

// Reasons reported on WorkflowAction for this generator.
const (
	rpReasonMigrated  = "migrated"
	rpReasonExisting  = "existing-release-please"
	rpReasonCustom    = "custom-release-please"
	rpReasonDirty     = "uncommitted-release-please"
	rpReasonDuplicate = "duplicate-release-please"
	rpReasonNoConfig  = "release-please-config"
)

// renderReleasePleaseCaller produces the caller for s.
func renderReleasePleaseCaller(s releasePleaseSettings) string {
	var b strings.Builder
	b.WriteString("# Generated by `kit init`. Edits will not be overwritten;\n")
	b.WriteString("# kit will surface conflicting refreshes as `.kit-suggested` siblings.\n")
	b.WriteString("# Runs release-please via the hop-top/.github release-please-on-push\n")
	b.WriteString("# reusable workflow: release-bot App token, one run per branch at a\n")
	b.WriteString("# time (newest push wins). Chain publish jobs on its outputs:\n")
	b.WriteString("#   needs: release-please\n")
	b.WriteString("#   if: needs.release-please.outputs.releases_created == 'true'\n\n")
	b.WriteString("name: release-please\n\non:\n")
	if len(s.Branches) > 0 {
		quoted := make([]string, len(s.Branches))
		for i, br := range s.Branches {
			quoted[i] = yamlScalar(br)
		}
		fmt.Fprintf(&b, "  push:\n    branches: [%s]\n", strings.Join(quoted, ", "))
	}
	if s.Dispatch {
		b.WriteString("  workflow_dispatch: {}\n")
	}
	b.WriteString("\npermissions:\n  contents: read\n\njobs:\n  release-please:\n")
	fmt.Fprintf(&b, "    uses: hop-top/.github/.github/workflows/%s@%s\n", releasePleaseReusable, workflowCallerRef)
	if s.ConfigFile != "" || s.ManifestFile != "" || s.TargetBranch != "" {
		b.WriteString("    with:\n")
		for _, kv := range [][2]string{
			{"config-file", s.ConfigFile},
			{"manifest-file", s.ManifestFile},
			{"target-branch", s.TargetBranch},
		} {
			if kv[1] != "" {
				fmt.Fprintf(&b, "      %s: %s\n", kv[0], yamlScalar(kv[1]))
			}
		}
	}
	b.WriteString("    secrets:\n")
	b.WriteString("      RELEASE_BOT_APP_ID: ${{ secrets.RELEASE_BOT_APP_ID }}\n")
	b.WriteString("      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}\n")
	return b.String()
}

var (
	plainScalarRe     = regexp.MustCompile(`^[A-Za-z0-9._][A-Za-z0-9._/-]*$`)
	ambiguousScalarRe = regexp.MustCompile(`^([-+]?[0-9._]+([eE][-+]?[0-9]+)?|(?i:true|false|yes|no|on|off|null|~))$`)
)

// yamlScalar renders v as a YAML scalar that reads back as the same
// string, in block and flow context alike.
func yamlScalar(v string) string {
	if plainScalarRe.MatchString(v) && !ambiguousScalarRe.MatchString(v) {
		return v
	}
	return "'" + strings.ReplaceAll(v, "'", "''") + "'"
}

// renderReleasePlease plans and applies the release-please caller for
// target, updating `.kit/generated.json`. Honors in.DryRun and
// in.MigrateReleasePlease. Returns one action per path it touched or
// reports on.
func renderReleasePlease(target string, in Inputs, now func() time.Time) ([]WorkflowAction, error) {
	if now == nil {
		now = time.Now
	}
	manifestPath := filepath.Join(target, filepath.FromSlash(manifestRelPath))
	manifest, err := readManifest(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("kit init: read manifest %q: %w", manifestPath, err)
	}
	index := manifest.index()

	found, err := scanReleasePleaseWorkflows(target)
	if err != nil {
		return nil, err
	}
	var live *releasePleaseWorkflow // a release-please workflow at the caller path
	var others []releasePleaseWorkflow
	for i := range found {
		if found[i].RelPath == releasePleaseCallerRel {
			live = &found[i]
		} else {
			others = append(others, found[i])
		}
	}

	abs := filepath.Join(target, filepath.FromSlash(releasePleaseCallerRel))
	suggested := abs + suggestedSuffix
	if !in.DryRun {
		if err := pruneAcceptedSuggestion(abs, suggested); err != nil {
			return nil, err
		}
	}
	existing, readErr := os.ReadFile(abs)
	exists := readErr == nil
	if readErr != nil && !os.IsNotExist(readErr) {
		return nil, fmt.Errorf("kit init: read %q: %w", abs, readErr)
	}
	entry, tracked := lookupManifest(manifest, index, releasePleaseCallerRel)
	managed := exists && tracked && sha256Hex(existing) == entry.SHA256

	// Settings: read back from what already runs release-please, so a
	// refresh or a suggestion reproduces it; defaults otherwise.
	settings := defaultReleasePleaseSettings(target, in)
	switch {
	case live != nil && live.Plain:
		settings = live.Settings
	case live == nil && len(others) == 1 && others[0].Plain:
		settings = others[0].Settings
	}
	planned := renderReleasePleaseCaller(settings)
	plannedHash := sha256Hex([]byte(planned))

	var actions []WorkflowAction
	dirty := false
	track := func(keepTimestamp bool) {
		at := now().UTC().Format(time.RFC3339)
		if keepTimestamp && tracked {
			at = entry.GeneratedAt
		}
		upsertManifest(manifest, index, ManifestEntry{Path: releasePleaseCallerRel, SHA256: plannedHash, GeneratedAt: at})
		dirty = true
	}
	writeLive := func(reason, detail string) error {
		if !in.DryRun {
			if err := writeWorkflowFile(abs, planned); err != nil {
				return err
			}
			if err := pruneAcceptedSuggestion(abs, suggested); err != nil {
				return err
			}
		}
		track(false)
		actions = append(actions, WorkflowAction{Path: releasePleaseCallerRel, Action: "write", Reason: reason, Detail: detail})
		return nil
	}
	suggest := func(reason, detail string) error {
		if !in.DryRun {
			if err := writeWorkflowFile(suggested, planned); err != nil {
				return err
			}
		}
		actions = append(actions, WorkflowAction{
			Path: releasePleaseCallerRel, Action: "suggest-sibling",
			SuggestedPath: releasePleaseCallerRel + suggestedSuffix, Reason: reason, Detail: detail,
		})
		return nil
	}
	remove := func(wf releasePleaseWorkflow, reason, detail string) error {
		if !in.DryRun {
			if err := removeFileIfExists(filepath.Join(target, filepath.FromSlash(wf.RelPath))); err != nil {
				return err
			}
		}
		actions = append(actions, WorkflowAction{Path: wf.RelPath, Action: "remove", Reason: reason, Detail: detail})
		return nil
	}
	keepOthers := func(reason string) {
		for _, wf := range others {
			actions = append(actions, WorkflowAction{
				Path: wf.RelPath, Action: "keep", Reason: reason,
				Detail: "also runs release-please; left untouched" + customSuffix(wf),
			})
		}
	}

	switch {
	case !exists:
		if len(others) == 0 {
			if err := writeLive("new", ""); err != nil {
				return nil, err
			}
			break
		}
		reason, detail, ok := migration(target, in, others)
		if !ok {
			if err := suggest(reason, detail); err != nil {
				return nil, err
			}
			keepOthers(reason)
			break
		}
		if err := writeLive(rpReasonMigrated, migratedDetail(others[0])); err != nil {
			return nil, err
		}
		if err := remove(others[0], rpReasonMigrated, "replaced by "+releasePleaseCallerRel); err != nil {
			return nil, err
		}

	case managed:
		if sha256Hex(existing) == plannedHash {
			track(true)
			actions = append(actions, WorkflowAction{Path: releasePleaseCallerRel, Action: "skip-unchanged"})
		} else if err := writeLive("refresh", ""); err != nil {
			return nil, err
		}
		for _, wf := range others {
			if in.MigrateReleasePlease && wf.Plain && gitClean(target, wf.RelPath) {
				if err := remove(wf, rpReasonDuplicate, "duplicated "+releasePleaseCallerRel); err != nil {
					return nil, err
				}
				continue
			}
			actions = append(actions, WorkflowAction{
				Path: wf.RelPath, Action: "keep", Reason: rpReasonDuplicate,
				Detail: "runs release-please alongside " + releasePleaseCallerRel +
					"; delete it (or rerun with --migrate-release-please when it is plain and committed)" + customSuffix(wf),
			})
		}

	case sha256Hex(existing) == plannedHash:
		// Convergence reclaim (Section 6): the untracked or edited file
		// already equals the render.
		if !in.DryRun {
			if err := removeFileIfExists(suggested); err != nil {
				return nil, err
			}
		}
		track(false)
		actions = append(actions, WorkflowAction{Path: releasePleaseCallerRel, Action: "manifest-update", Reason: "convergence"})
		keepOthers(rpReasonDuplicate)

	case tracked || live == nil:
		// Kit's own caller, edited by hand — or an unrelated file at the
		// caller path. Section 6: never overwrite.
		if err := suggest("user-edited", ""); err != nil {
			return nil, err
		}
		keepOthers(rpReasonDuplicate)

	default:
		// A hand-written release-please workflow at the caller path.
		reason, detail, ok := migration(target, in, append([]releasePleaseWorkflow{*live}, others...))
		if !ok {
			if err := suggest(reason, detail); err != nil {
				return nil, err
			}
			keepOthers(reason)
			break
		}
		if err := writeLive(rpReasonMigrated, migratedDetail(*live)); err != nil {
			return nil, err
		}
	}

	actions = append(actions, missingConfigActions(target, settings)...)

	if dirty && !in.DryRun {
		if err := writeWorkflowManifest(manifestPath, manifest); err != nil {
			return nil, fmt.Errorf("kit init: write manifest %q: %w", manifestPath, err)
		}
	}
	return actions, nil
}

// migration decides whether the single hand-written release-please
// workflow in wfs may be replaced by the caller. When it may not, it
// returns the reason and the explanation to report.
func migration(target string, in Inputs, wfs []releasePleaseWorkflow) (reason, detail string, ok bool) {
	if len(wfs) > 1 {
		paths := make([]string, len(wfs))
		for i, wf := range wfs {
			paths[i] = wf.RelPath
		}
		return rpReasonExisting, "several workflows run release-please (" + strings.Join(paths, ", ") +
			"); reduce them to one by hand, then rerun", false
	}
	wf := wfs[0]
	switch {
	case !wf.Plain:
		return rpReasonCustom, wf.RelPath + " runs release-please with more than the caller reproduces (" +
			wf.Why + "); kit never rewrites it. Move its extra jobs onto the suggested caller's outputs by hand, " +
			"then delete it", false
	case !in.MigrateReleasePlease:
		return rpReasonExisting, wf.RelPath + " already runs release-please; rerun with --migrate-release-please " +
			"to replace it with the suggested caller", false
	case !gitClean(target, wf.RelPath):
		return rpReasonDirty, wf.RelPath + " is not committed as-is in git; commit or discard its changes " +
			"so the replaced content stays recoverable, then rerun with --migrate-release-please", false
	}
	return "", "", true
}

func migratedDetail(wf releasePleaseWorkflow) string {
	d := "replaces " + wf.RelPath
	switch wf.Token {
	case "", "the release-bot App":
	default:
		d += "; release-please now authenticates as the release-bot App instead of " + wf.Token +
			" (RELEASE_BOT_APP_ID / RELEASE_BOT_PRIVATE_KEY must reach this repo)"
	}
	return d
}

func customSuffix(wf releasePleaseWorkflow) string {
	if wf.Plain {
		return ""
	}
	return " (custom: " + wf.Why + ")"
}

// missingConfigActions reports a missing release-please config or
// manifest at the paths the caller passes.
func missingConfigActions(target string, s releasePleaseSettings) []WorkflowAction {
	cfg, man := s.ConfigFile, s.ManifestFile
	if cfg == "" {
		cfg = releasePleaseDefaultConfig
	}
	if man == "" {
		man = releasePleaseDefaultManifest
	}
	cfgOK, manOK := fileExists(target, cfg), fileExists(target, man)
	switch {
	case cfgOK && manOK:
		return nil
	case !cfgOK && !manOK:
		return []WorkflowAction{{
			Path: cfg, Action: "missing", Reason: rpReasonNoConfig,
			Detail: "no " + cfg + " or " + man + ": release-please runs skip until both exist " +
				"(shape: hop-top/.github docs/bootstrap-checklist.md, section 5)",
		}}
	}
	missing := cfg
	if cfgOK {
		missing = man
	}
	return []WorkflowAction{{
		Path: missing, Action: "missing", Reason: rpReasonNoConfig,
		Detail: "release-please runs fail until " + missing + " exists",
	}}
}

// defaultReleasePleaseSettings: push on the default branch plus manual
// dispatch; config paths follow where an existing config lives.
func defaultReleasePleaseSettings(target string, in Inputs) releasePleaseSettings {
	branch := originHeadBranch(target)
	if branch == "" {
		branch = in.DefaultBranch
	}
	if branch == "" {
		branch = "main"
	}
	s := releasePleaseSettings{Branches: []string{branch}, Dispatch: true}
	orgLayout := fileExists(target, releasePleaseDefaultConfig) || fileExists(target, releasePleaseDefaultManifest)
	rootLayout := fileExists(target, actionDefaultConfig) || fileExists(target, actionDefaultManifest)
	if !orgLayout && rootLayout {
		s.ConfigFile, s.ManifestFile = actionDefaultConfig, actionDefaultManifest
	}
	return s
}

// originHeadBranch returns the branch origin/HEAD points at, or "".
func originHeadBranch(dir string) string {
	if !isGitWorkTree(dir) {
		return ""
	}
	out, err := runGitIn(dir, "symbolic-ref", "--quiet", "--short", "refs/remotes/origin/HEAD")
	if err != nil {
		return ""
	}
	return strings.TrimPrefix(out, "origin/")
}

// gitClean reports whether rel is tracked and identical to HEAD (index
// and worktree), i.e. whatever kit replaces is recoverable from git.
func gitClean(dir, rel string) bool {
	if !isGitWorkTree(dir) {
		return false
	}
	if _, err := runGitIn(dir, "ls-files", "--error-unmatch", "--", rel); err != nil {
		return false
	}
	_, err := runGitIn(dir, "diff", "--quiet", "HEAD", "--", rel)
	return err == nil
}

// isGitWorkTree: dir itself is the top of a git work tree. Checked
// first so git never answers for an unrelated repo enclosing dir.
func isGitWorkTree(dir string) bool {
	top, err := runGitIn(dir, "rev-parse", "--show-toplevel")
	if err != nil {
		return false
	}
	a, errA := filepath.EvalSymlinks(top)
	b, errB := filepath.EvalSymlinks(dir)
	return errA == nil && errB == nil && a == b
}

func fileExists(root, rel string) bool {
	info, err := os.Stat(filepath.Join(root, filepath.FromSlash(rel)))
	return err == nil && !info.IsDir()
}

// scanReleasePleaseWorkflows returns every workflow under
// `.github/workflows/` that runs release-please, sorted by path.
func scanReleasePleaseWorkflows(target string) ([]releasePleaseWorkflow, error) {
	dir := filepath.Join(target, ".github", "workflows")
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("kit init: list %q: %w", dir, err)
	}
	var out []releasePleaseWorkflow
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || (filepath.Ext(name) != ".yml" && filepath.Ext(name) != ".yaml") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, fmt.Errorf("kit init: read %q: %w", name, err)
		}
		if wf, ok := classifyReleasePleaseWorkflow(".github/workflows/"+name, data); ok {
			out = append(out, wf)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].RelPath < out[j].RelPath })
	return out, nil
}
