// Tests for the release-please caller generator (releaseplease.go):
// rendering, fresh-repo wiring, config-location detection, idempotent
// re-runs and the flag plumbing. Migration of hand-written workflows
// lives in releaseplease_migrate_test.go.
package kitinit

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"

	tmpl "hop.top/kit/internal/template"
)

const rpCaller = ".github/workflows/release-please.yml"

func rpInputs() Inputs {
	return Inputs{
		DefaultBranch:        "main",
		WithGitHubWorkflows:  true,
		WithReleasePlease:    true,
		MigrateReleasePlease: false,
	}
}

func writeRel(t *testing.T, root, rel, body string) {
	t.Helper()
	p := filepath.Join(root, filepath.FromSlash(rel))
	require.NoError(t, os.MkdirAll(filepath.Dir(p), 0o750))
	require.NoError(t, os.WriteFile(p, []byte(body), 0o644))
}

func readRel(t *testing.T, root, rel string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	require.NoError(t, err)
	return string(b)
}

func assertAbsent(t *testing.T, root, rel string) {
	t.Helper()
	_, err := os.Stat(filepath.Join(root, filepath.FromSlash(rel)))
	assert.True(t, os.IsNotExist(err), "%s must not exist", rel)
}

func findAction(actions []WorkflowAction, path string) (WorkflowAction, bool) {
	for _, a := range actions {
		if a.Path == path {
			return a, true
		}
	}
	return WorkflowAction{}, false
}

func mustAction(t *testing.T, actions []WorkflowAction, path string) WorkflowAction {
	t.Helper()
	a, ok := findAction(actions, path)
	require.True(t, ok, "no action for %s in %+v", path, actions)
	return a
}

// parseWorkflow decodes a rendered workflow into a generic map.
func parseWorkflow(t *testing.T, content string) map[string]any {
	t.Helper()
	var doc map[string]any
	require.NoError(t, yaml.Unmarshal([]byte(content), &doc), content)
	return doc
}

// --- rendering -------------------------------------------------------------

func TestRenderReleasePleaseCaller_Defaults(t *testing.T) {
	got := renderReleasePleaseCaller(releasePleaseSettings{Branches: []string{"main"}, Dispatch: true})
	doc := parseWorkflow(t, got)

	assert.Equal(t, "release-please", doc["name"])
	on := doc["on"].(map[string]any)
	assert.Equal(t, map[string]any{"branches": []any{"main"}}, on["push"])
	assert.Contains(t, on, "workflow_dispatch")
	assert.Equal(t, map[string]any{"contents": "read"}, doc["permissions"])
	// The concurrency guard lives in the reusable workflow's job; a
	// workflow-level guard here would also cancel publish jobs chained
	// on a previous run's outputs.
	assert.NotContains(t, doc, "concurrency")

	job := doc["jobs"].(map[string]any)["release-please"].(map[string]any)
	assert.Equal(t, "hop-top/.github/.github/workflows/release-please-on-push.yml@"+workflowCallerRef, job["uses"])
	assert.NotContains(t, job, "with", "defaults must not be spelled out")
	assert.Equal(t, map[string]any{
		"RELEASE_BOT_APP_ID":      "${{ secrets.RELEASE_BOT_APP_ID }}",
		"RELEASE_BOT_PRIVATE_KEY": "${{ secrets.RELEASE_BOT_PRIVATE_KEY }}",
	}, job["secrets"])
	assert.True(t, strings.HasPrefix(got, "# Generated by `kit init`."))
}

func TestRenderReleasePleaseCaller_CarriesSettings(t *testing.T) {
	got := renderReleasePleaseCaller(releasePleaseSettings{
		Branches:     []string{"main", "next"},
		Dispatch:     true,
		ConfigFile:   "release-please-config.json",
		ManifestFile: ".release-please-manifest.json",
		TargetBranch: "release/1.x",
	})
	doc := parseWorkflow(t, got)
	on := doc["on"].(map[string]any)
	assert.Equal(t, []any{"main", "next"}, on["push"].(map[string]any)["branches"])
	job := doc["jobs"].(map[string]any)["release-please"].(map[string]any)
	assert.Equal(t, map[string]any{
		"config-file":   "release-please-config.json",
		"manifest-file": ".release-please-manifest.json",
		"target-branch": "release/1.x",
	}, job["with"])
}

func TestRenderReleasePleaseCaller_DispatchOnly(t *testing.T) {
	doc := parseWorkflow(t, renderReleasePleaseCaller(releasePleaseSettings{Dispatch: true}))
	on := doc["on"].(map[string]any)
	assert.NotContains(t, on, "push")
	assert.Contains(t, on, "workflow_dispatch")
}

func TestRenderReleasePleaseCaller_RoundTripsThroughClassifier(t *testing.T) {
	for _, s := range []releasePleaseSettings{
		{Branches: []string{"main"}, Dispatch: true},
		{Branches: []string{"main", "next"}, Dispatch: true, TargetBranch: "next"},
		{Dispatch: true, ConfigFile: "rp.json", ManifestFile: "rp-manifest.json"},
		{Branches: []string{"trunk"}},
	} {
		content := renderReleasePleaseCaller(s)
		wf, isRP := classifyReleasePleaseWorkflow(rpCaller, []byte(content))
		require.True(t, isRP, content)
		require.True(t, wf.Plain, "%s: %s", wf.Why, content)
		assert.Equal(t, s, wf.Settings)
	}
}

// --- fresh repo --------------------------------------------------------------

func TestRenderReleasePlease_Fresh_WritesCallerAndTracksIt(t *testing.T) {
	target := t.TempDir()
	actions, err := renderReleasePlease(target, rpInputs(), fixedNow())
	require.NoError(t, err)

	a := mustAction(t, actions, rpCaller)
	assert.Equal(t, "write", a.Action)
	assert.Equal(t, "new", a.Reason)
	content := readRel(t, target, rpCaller)
	assert.Equal(t, renderReleasePleaseCaller(releasePleaseSettings{Branches: []string{"main"}, Dispatch: true}), content)

	m := readManifestFile(t, target)
	require.Len(t, m.Files, 1)
	assert.Equal(t, rpCaller, m.Files[0].Path)
	assert.Equal(t, sha256Hex([]byte(content)), m.Files[0].SHA256)
}

func TestRenderReleasePlease_OrgConfigPresent_NoMissingReport(t *testing.T) {
	target := t.TempDir()
	writeRel(t, target, ".github/release-please-config.json", `{"packages":{".":{}}}`)
	writeRel(t, target, ".github/.release-please-manifest.json", `{}`)
	actions, err := renderReleasePlease(target, rpInputs(), fixedNow())
	require.NoError(t, err)
	_, ok := findAction(actions, ".github/release-please-config.json")
	assert.False(t, ok, "%+v", actions)
}

func TestRenderReleasePlease_OneConfigFileMissing_Reported(t *testing.T) {
	target := t.TempDir()
	writeRel(t, target, ".github/release-please-config.json", `{"packages":{".":{}}}`)
	actions, err := renderReleasePlease(target, rpInputs(), fixedNow())
	require.NoError(t, err)
	a := mustAction(t, actions, ".github/.release-please-manifest.json")
	assert.Equal(t, "missing", a.Action)
}

func TestRenderReleasePlease_RootConfig_CallerPointsAtIt(t *testing.T) {
	target := t.TempDir()
	writeRel(t, target, "release-please-config.json", `{"packages":{".":{}}}`)
	writeRel(t, target, ".release-please-manifest.json", `{}`)
	actions, err := renderReleasePlease(target, rpInputs(), fixedNow())
	require.NoError(t, err)

	doc := parseWorkflow(t, readRel(t, target, rpCaller))
	job := doc["jobs"].(map[string]any)["release-please"].(map[string]any)
	assert.Equal(t, map[string]any{
		"config-file":   "release-please-config.json",
		"manifest-file": ".release-please-manifest.json",
	}, job["with"])
	_, ok := findAction(actions, "release-please-config.json")
	assert.False(t, ok, "root config exists: nothing to report; got %+v", actions)
}

func TestRenderReleasePlease_DefaultBranchInput(t *testing.T) {
	target := t.TempDir()
	in := rpInputs()
	in.DefaultBranch = "trunk"
	_, err := renderReleasePlease(target, in, fixedNow())
	require.NoError(t, err)
	on := parseWorkflow(t, readRel(t, target, rpCaller))["on"].(map[string]any)
	assert.Equal(t, []any{"trunk"}, on["push"].(map[string]any)["branches"])
}

func TestRenderReleasePlease_DryRun_WritesNothing(t *testing.T) {
	target := t.TempDir()
	in := rpInputs()
	in.DryRun = true
	actions, err := renderReleasePlease(target, in, fixedNow())
	require.NoError(t, err)
	assert.Equal(t, "write", mustAction(t, actions, rpCaller).Action)
	entries, err := os.ReadDir(target)
	require.NoError(t, err)
	assert.Empty(t, entries, "dry-run must not touch disk")
}

// --- idempotency -------------------------------------------------------------

func TestRenderReleasePlease_Rerun_SkipsUnchanged(t *testing.T) {
	target := t.TempDir()
	_, err := renderReleasePlease(target, rpInputs(), fixedNow())
	require.NoError(t, err)
	before := readRel(t, target, rpCaller)
	manifestBefore := readRel(t, target, manifestRelPath)

	actions, err := renderReleasePlease(target, rpInputs(), fixedNow())
	require.NoError(t, err)
	assert.Equal(t, "skip-unchanged", mustAction(t, actions, rpCaller).Action)
	assert.Equal(t, before, readRel(t, target, rpCaller))
	assert.Equal(t, manifestBefore, readRel(t, target, manifestRelPath))
	assertAbsent(t, target, rpCaller+suggestedSuffix)
}

// A managed caller carrying non-default settings must survive a re-run
// that resolves different defaults: settings are read back from the
// caller itself, not re-derived.
func TestRenderReleasePlease_Rerun_KeepsCarriedSettings(t *testing.T) {
	target := t.TempDir()
	writeRel(t, target, "release-please-config.json", `{"packages":{".":{}}}`)
	writeRel(t, target, ".release-please-manifest.json", `{}`)
	in := rpInputs()
	in.DefaultBranch = "trunk"
	_, err := renderReleasePlease(target, in, fixedNow())
	require.NoError(t, err)
	before := readRel(t, target, rpCaller)

	// Second run: different --default-branch, config moved under .github/.
	writeRel(t, target, ".github/release-please-config.json", `{"packages":{".":{}}}`)
	actions, err := renderReleasePlease(target, rpInputs(), fixedNow())
	require.NoError(t, err)
	assert.Equal(t, "skip-unchanged", mustAction(t, actions, rpCaller).Action)
	assert.Equal(t, before, readRel(t, target, rpCaller))
}

func TestRenderReleasePlease_ManagedCallerEdited_SuggestsSibling(t *testing.T) {
	target := t.TempDir()
	_, err := renderReleasePlease(target, rpInputs(), fixedNow())
	require.NoError(t, err)
	edited := readRel(t, target, rpCaller) + `
  publish:
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo publish
`
	writeRel(t, target, rpCaller, edited)

	in := rpInputs()
	in.MigrateReleasePlease = true // never applies to kit's own (edited) caller
	actions, err := renderReleasePlease(target, in, fixedNow())
	require.NoError(t, err)
	a := mustAction(t, actions, rpCaller)
	assert.Equal(t, "suggest-sibling", a.Action)
	assert.Equal(t, "user-edited", a.Reason)
	assert.Equal(t, edited, readRel(t, target, rpCaller), "user edit must survive")
}

// --- detection -----------------------------------------------------------------

func TestClassify_IgnoresMentionsOutsideUses(t *testing.T) {
	// The preflight caller names release-please in paths and comments
	// but never runs it.
	body := `# Checks googleapis/release-please-action config.
name: release-please-preflight
on:
  pull_request:
    paths: ['.github/workflows/release-please.yml']
jobs:
  preflight:
    uses: hop-top/.github/.github/workflows/release-please-preflight.yml@v0
`
	_, isRP := classifyReleasePleaseWorkflow(".github/workflows/release-please-preflight.yml", []byte(body))
	assert.False(t, isRP)
}

func TestClassify_UnparseableMentioningTheActionIsCustom(t *testing.T) {
	body := "jobs:\n  rp:\n    steps:\n      - uses: googleapis/release-please-action@v4\n  bad: [\n"
	wf, isRP := classifyReleasePleaseWorkflow(".github/workflows/x.yml", []byte(body))
	assert.True(t, isRP)
	assert.False(t, wf.Plain)
}

// --- plumbing ------------------------------------------------------------------

func TestGather_ReleasePleaseFlags(t *testing.T) {
	in, err := Gather(t.Context(), []string{"demo"}, &FlagSet{}, tmpl.Manifest{}, Defaults{}, nil)
	require.NoError(t, err)
	assert.True(t, in.WithReleasePlease, "release-please caller is on by default")
	assert.False(t, in.MigrateReleasePlease, "migration is opt-in")

	off, on := false, true
	in, err = Gather(t.Context(), []string{"demo"},
		&FlagSet{WithReleasePlease: &off, MigrateReleasePlease: &on}, tmpl.Manifest{}, Defaults{}, nil)
	require.NoError(t, err)
	assert.False(t, in.WithReleasePlease)
	assert.True(t, in.MigrateReleasePlease)
}

func TestApplyReleasePleaseFlags(t *testing.T) {
	cases := []struct {
		argv        []string
		wantWith    *bool
		wantMigrate *bool
	}{
		{nil, nil, nil},
		{[]string{"--without-release-please"}, boolp(false), nil},
		{[]string{"--with-release-please=false"}, boolp(false), nil},
		{[]string{"--with-release-please", "--without-release-please"}, boolp(false), nil},
		{[]string{"--migrate-release-please"}, nil, boolp(true)},
	}
	for _, c := range cases {
		cmd := InitCmd(nil)
		require.NoError(t, cmd.ParseFlags(c.argv))
		fs := &FlagSet{}
		applyReleasePleaseFlags(cmd, fs)
		assert.Equal(t, c.wantWith, fs.WithReleasePlease, "%v", c.argv)
		assert.Equal(t, c.wantMigrate, fs.MigrateReleasePlease, "%v", c.argv)
	}
}

func boolp(b bool) *bool { return &b }

// --- git fixtures (shared with the migration tests) ------------------------------

// rpGit runs git in dir (GIT_* scrubbed by gitRun) with a throwaway
// identity so commits work on any machine.
func rpGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	gitRun(t, "", append([]string{
		"-C", dir,
		"-c", "user.name=kit-test", "-c", "user.email=kit-test@example.com",
		"-c", "commit.gpgsign=false", "-c", "init.defaultBranch=main",
	}, args...)...)
}

// gitRepoWith creates a git repo holding files, all committed.
func gitRepoWith(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	rpGit(t, dir, "init", "-q")
	for rel, body := range files {
		writeRel(t, dir, rel, body)
	}
	rpGit(t, dir, "add", "-A")
	rpGit(t, dir, "commit", "-q", "-m", "seed")
	return dir
}

// --- wiring into bootstrap / augment ---------------------------------------------

func TestBootstrap_RendersReleasePleaseCaller(t *testing.T) {
	in := e2eInputs("rpdemo", false)
	in.WithReleasePlease = true
	target, sum := e2eBootstrap(t, in)
	assert.FileExists(t, filepath.Join(target, filepath.FromSlash(rpCaller)))
	assert.Equal(t, "write", mustAction(t, sum.Workflows, rpCaller).Action)
	assert.Contains(t, manifestPaths(t, []byte(readRel(t, target, manifestRelPath))), rpCaller)
}

func TestBootstrap_WithoutReleasePlease_NoCaller(t *testing.T) {
	in := e2eInputs("rpoff", false)
	in.WithReleasePlease = false
	target, sum := e2eBootstrap(t, in)
	assertAbsent(t, target, rpCaller)
	_, ok := findAction(sum.Workflows, rpCaller)
	assert.False(t, ok)
	// The other callers are unaffected.
	assert.FileExists(t, filepath.Join(target, ".github", "workflows", "release-go-caller.yml"))
}

func TestBootstrap_WithoutGitHubWorkflows_NoReleasePleaseCaller(t *testing.T) {
	in := e2eInputs("rpnogh", false)
	in.WithReleasePlease = true
	in.WithGitHubWorkflows = false
	target, _ := e2eBootstrap(t, in)
	assertAbsent(t, target, rpCaller)
}

func TestAugment_ReleasePlease_MigratesAndIsIdempotent(t *testing.T) {
	tplPath := fixtureTemplate(t)
	cwd := gitRepoWith(t, map[string]string{rpCaller: legacyAppToken})
	deps, _ := fixtureDeps()
	in := baseInputs(tplPath, "demo", 1)
	in.Runtime = []string{"go"}
	in.DefaultBranch = "main"
	in.WithGitHubWorkflows = true
	in.WithReleasePlease = true
	in.MigrateReleasePlease = true

	sum, err := runAugment(t.Context(), deps, in, cwd)
	require.NoError(t, err)
	assert.Equal(t, "migrated", mustAction(t, sum.Workflows, rpCaller).Reason)
	live := readRel(t, cwd, rpCaller)

	sum, err = runAugment(t.Context(), deps, in, cwd)
	require.NoError(t, err)
	assert.Equal(t, "skip-unchanged", mustAction(t, sum.Workflows, rpCaller).Action)
	assert.Equal(t, live, readRel(t, cwd, rpCaller))
}
